ferrocene/tools/pull-subtrees/pull.py
When no previous commit created by the automation was found, and the subtree pull didn't result in any change, the automation would fail as it'd try to create a GitHub PR without any diff. This changes the automation to detect whether a subtree pull was actually committed.
=> Fix failure to create pull requests in pull-subtrees

src/bootstrap/download-ci-llvm-stamp
Due to the squash, bootstrap isn't able to determine the commit that last updated LLVM. This bump should fix it.
=> Bump download-ci-llvm-stamp

.github/dependabot.yml
This PR configures dependabot to update the dependencies in the monorepo automatically, both for the majority of crates and for bootstrap. This is configured to open a weekly PR on Monday morning, and to group all updates in a single PR.
=> Automate dependency updates with dependabot

ferrocene/doc/user-manual/src/targets/index.rst
Just noticed while browsing around that the experimental targets table in the user manual was not consistent with the supported targets table. This PR changes it to add the "kind" column.
=> Make experimental targets table consistent

.github/dependabot.yml
Apparently there is no validation done ahead of merging a PR, thrilling. Errors are described in https://github.com/ferrocene/ferrocene/runs/17814290458.
=> Fix errors in the dependabot configuration

ferrocene/tools/traceability-matrix/src/test_outcomes.rs
Before this PR, the traceability matrix code to load test outcomes filtered which suites to load by checking whether any of the parent steps were of the `bootstrap::test::Compiletest` type.
A recent upstream refactor shuffled things around and moved that type to `bootstrap::core::build_steps::test::Compiletest`. The type rename caused the code to think those tests were not run by compiletest, which resulted in them being ignored.
The check wasn't actually needed anymore. It was needed before upstream introduced the v1 metrics format, which didn't have any structured metadata on what kind of test suite was invoked. This is not a concern in v1 build metrics though, as they include the test suite kind in the `TestSuiteMetadata` struct.
Thus, this PR changes the logic to check the structured …
=> Fix traceability matrix not including any tests

ferrocene/ci/scripts/calculate-release-job-matrix.py
I noticed a corner case in the release scheduler that could lead to unpredictable commits being releases. More details are available in the comments.
=> Fix inconsistent behavior from the release scheduler

ferrocene/doc/qualification-report/src/tests.rst
The reshuffling of the files inside of bootstrap affected the list of test suite summaries in the qualification report (in addition to the traceability matrix, see #64). This PR fixes that by updating the types.
=> Fix test suite summaries after bootstrap reshuffling

ferrocene/tools/common/pr_links.py, ferrocene/tools/pull-subtrees/pull.py, ferrocene/tools/pull-upstream/generate_pr_body.py
Before this PR, every pull request mentioned in an automated pull from upstream or a subtree would include a link to the pulled PR in the form of `repo#number`. GitHub then used that to include a link to the PR, and automatically insert the PR title.
Unfortunately, doing so also resulted in a "backlink" event being included in the target PR. That is indeed annoying, and caused a fair amount of spam in `rust-lang/rust`. We asked GitHub Support, but there isn't an officially supported way to prevent those backlinks from being generated.
To solve the problem, this PR implements custom code to generate the links in automated PRs, crucially using `www.github.com` rather than `github.com` as the domain name. It turns out that adding www to the domain prevents backlinks from being created, which …
=> remove backlinks from automated PRs

ferrocene/ci/configure.sh, ferrocene/doc/internal-procedures/src/setup-local-env.rst
Using the configure script to setup a local development environment is usually not a good idea, as that is meant to be used as part of our CI, and some of its settings hamper local development (for example, it rebuilds everything as soon as a new git commit is made).
To guide developers in not using the script, running it outside CI will now error out, pointing people to the internal procedures doc. There is an escape hatch if someone really needs it, which is pointed out in the error message.
This also updates the suggested `config.toml` with the new change tracking introduced upstream.
=> Prevent `ferrocene/ci/configure.sh` from being invoked locally

compiler/rustc_target/src/spec/mod.rs, compiler/rustc_target/src/spec/targets/aarch64_unknown_ferrocenecoretest.rs, compiler/rustc_target/src/spec/targets/aarch64_unknown_none.rs, compiler/rustc_target/src/spec/targets/x86_64_unknown_linux_gnu.rs
1) Switch x86_64-linux-gnu to use lld.
Using the bundled `rust-lld` as the linker (via its `ld.lld` wrapper) means all users always use the same linker. This helps with the qualification efforts, rather than users using random versions of `ld`.
However, we still drive `rust-lld` (or actually `ld.lld`) via the system C compiler, because the C compiler knows where the system libraries live, and Rust does not.
2) Switch the aarch64-unknown-none target to use rust-lld.
Using the bundled `rust-lld` as the linker (via its `ld.lld` wrapper) means all users always use the same linker. This helps with the qualification efforts, rather than users using random versions of `ld`.
We don't go via the system C compiler on `aarch64-unknown-none` because we do not need system C libraries. We do go via the …
=> Draft: Use LLD instead of LD for our three targets

config.example.toml, ferrocene/ci/configure.sh, ferrocene/doc/index/index-assets/index.css, ferrocene/doc/index/index-assets/subset-filters/signatures.css, ferrocene/doc/index/index-assets/subset-filters/signatures.css.ferrocene-subset, ferrocene/doc/index/index.html, src/bootstrap/src/core/builder.rs, src/bootstrap/src/core/config/config.rs, src/bootstrap/src/ferrocene/dist.rs, src/bootstrap/src/ferrocene/doc.rs
This PR adds the infrastructure needed to include the technical report from TÜV into the generated documentation, by setting a key in `config.toml` pointing to the file in S3. Right now that is not configured in CI, as it's supposed to be used only on stable releases.
Two changes to the rest of Ferrocene were needed to make this work:
* There is now a way to hide some elements from the index based on the subsets the customer has access to. This is accomplished by hiding all elements with a `data-subset` HTML attribute by default, and having per-subset CSS files that show the subset's elements.
* There is now a way to include individual files in a subset by creating a file called `$name.ferrocene-subset`. The file behaves like a `ferrocene-subset` file inside a directory, but it only …
=> Add infra to include the technical report in the built docs

src/bootstrap/src/ferrocene/dist.rs
`trim` is already called 2 lines prior
=> remove redundant call

ferrocene/tools/pull-upstream/pull.sh
In https://github.com/ferrocene/ferrocene/pull/109 we noticed another way automated pulls could fail: the `Cargo.lock` requiring to be regenerated due to the custom Ferrocene tools we have in the repository. This PR prevents these problems from showing up in the future by regenerating the lockfile every single pull, if needed.
=> Automatically update Cargo.lock during upstream pulls

.github/workflows/automation-pull-upstream.yml, ferrocene/tools/pull-upstream/generate_pr_body.py
There was a long standing bug in the script used to generate upstream pulls' PR bodies: if followup commits were present on the branch, the script would not output anything. Up until today this only happened if the script was ran locally after committing extra changes, but since #112 the automation itself can generate followup commits.
This PR fixes the bug by walking back the commit graph until a merge commit is found, rather than the current behavior of always using the last commit even if it's not a merge commit.
This PR also speeds up the execution of the automation in CI, as most of the time right now is spent cloning LLVM. The CI script to download a shallow clone of a subset of it is now used instead.
=> Fix PR message not being generated during some upstream pulls

src/bootstrap/src/ferrocene/test.rs
While preparing the open sourcing of Ferrocene 23.06, I stumbled upon ferrocene/ferrocene-prehistory#1454. As part of the fix, that PR accidentally switched the step executed when requesting the `generated-tarball` tests. This PR fixes that.
=> Actually run tests for `generate-tarball`

ferrocene/tools/self-test/src/error.rs, ferrocene/tools/self-test/src/linkers.rs, ferrocene/tools/self-test/src/main.rs, ferrocene/tools/self-test/src/targets.rs, ferrocene/tools/self-test/src/test_utils.rs
* Only some targets now need a C compiler, the others use LLD directly
* We need to know what the C compiler is called (`cc`, `gcc`, `clang`, etc)
* We need to check the C compiler supports `-fuse-ld=lld`
* We need to check the C compiler supports `-B/path/to/tools`
* We check if the linker is being given LTO related arguments by the C compiler and, if so, turn that off.
* We need to tell the user what linker args we used to build their binary
=> Teaching ferrocene-self-test how to check the C compiler

ferrocene/doc/safety-manual/src/options.rst, ferrocene/doc/safety-manual/src/procedures.rst, ferrocene/doc/user-manual/src/self-test/error-codes.rst, ferrocene/doc/user-manual/src/targets/aarch64-unknown-none.rst, ferrocene/doc/user-manual/src/targets/x86_64-unknown-linux-gnu.rst
Updates the docs for `aarch64-unknown-none` and `x86_64-unknown-linux-gnu` to reflect our new choices around which linker we use (see #10)
=> Update target docs.

rustfmt.toml
The subtree was removed, but the rustfmt instruction was not.
=> remove reference to non-existent repo

.circleci/workflows.yml, src/stage0.json
This PR reverts the temporary commit used to make the initial CI job for 1.68 pass in the new repo.
=> Revert temporary commit in 1.68

.circleci/workflows.yml, ferrocene/packages.toml, src/bootstrap/src/ferrocene/partners/oxidos.rs
#157 disabled building OxidOS in CI due to the `core_intrinsics` unstable feature being marked as internal by upstream. This PR re-enables it, and changes bootstrap to allow internal features when building OxidOS.
=> Re-enable OxidOS in CI

ferrocene/doc/safety-manual/src/options.rst, ferrocene/tools/self-test/sample-programs/assertion.rs, ferrocene/tools/self-test/src/compile.rs, ferrocene/tools/self-test/src/error.rs, ferrocene/tools/self-test/src/linkers.rs
We now give the C compiler a `-Wl,--foobar` argument, and test that the linker receives `--foobar` as an argument (but using a long random string instead of `foobar`).
=> Ferrocene Self Test: Check C compiler passes extra args.

ferrocene/doc/specification/exts/ferrocene_spec/paragraph_ids.py, ferrocene/doc/sphinx-shared-resources/exts/ferrocene_qualification/document_id.py, ferrocene/doc/sphinx-shared-resources/exts/ferrocene_qualification/signature_page.py, ferrocene/doc/user-manual/exts/ferrocene_user_manual/traceability_ids.py, ferrocene/packages.toml, src/bootstrap/src/core/builder.rs, src/bootstrap/src/ferrocene/dist.rs, src/bootstrap/src/ferrocene/doc.rs, src/bootstrap/src/ferrocene/run.rs, src/bootstrap/src/ferrocene/sign.rs
This PR adds a new dist step that generates an *internal* `ferrocene-docs-doctrees` tarball, which contains the XML serialization of Sphinx's AST (the docutils doctrees). There is no use for the tarball right now, but a thing I'd like to build in the near future is a tool to generate a semantic diff of the documentation between two versions (so that we can easily give a changelog to TÜV), and that requires having the doctrees of old versions.
The tarball is internal not because it contains sensitive info (it's a different representation of the same info after all), but because showing it in the download pages to users would be super confusing.
This also changes some Sphinx extensions to output their files only when building HTML.
This PR is best reviewed commit-by-commit.
=> Generate the internal `ferrocene-docs-doctrees` tarball

ferrocene/doc/qualification-report/src/tests.rst, ferrocene/doc/safety-manual/src/environment.rst, ferrocene/doc/sphinx-shared-resources/exts/ferrocene_qualification/__init__.py, ferrocene/doc/sphinx-shared-resources/exts/ferrocene_qualification/target.py, ferrocene/doc/sphinx-shared-resources/themes/ferrocene/static/ferrocene.css, ferrocene/doc/target-names.toml, ferrocene/doc/user-manual/src/targets/aarch64-unknown-none.rst, ferrocene/doc/user-manual/src/targets/index.rst, ferrocene/doc/user-manual/src/targets/x86_64-unknown-linux-gnu.rst, src/bootstrap/src/ferrocene/doc.rs
This PR adds a new role to the `ferrocene_qualification` extension: `:target:`. The role converts the target triple into the human-readable name based on the new `ferrocene/doc/target-names.toml`. The purpose of this is twofold:
* It increases consistency across the documents, as we have a single place where they are defined.
* It helps with a WIP PR I'm working on to split the [test results](https://public-docs.ferrocene.dev/main/qualification/report/tests.html) page into per-target pages, as it means the rest of the automation can fetch the human-readable target name programmatically.
=> Create central table of human-readable target names

ferrocene/doc/internal-procedures/src/release/stable.rst, ferrocene/doc/qualification-plan/src/index.rst, ferrocene/doc/qualification-plan/src/patching.rst
This PR adds a new page to the qualification plan called "Patching process", which describes the process we must follow to publish bug fix releases without going through full requalification.
=> Add patching process to the qualification plan

ferrocene/doc/scope.rst
Spelled the wrong letter when preparing the file :sweat_smile:
=> Fix wrong variable used in `scope.rst`

tests/ui/ferrocene/compiler-arguments/llvm-args/protect-from-escaped-allocas-true.rs, tests/ui/for-loop-while/label_break_value.rs, tests/ui/label/label_break_value_continue.rs, tests/ui/label/label_break_value_unlabeled_break.rs, tests/ui/rfcs/rfc-2627-raw-dylib/link-ordinal-and-name.rs, tests/ui/rfcs/rfc-2627-raw-dylib/link-ordinal-invalid-format.rs, tests/ui/rfcs/rfc-2627-raw-dylib/link-ordinal-missing-argument.rs, tests/ui/rfcs/rfc-2627-raw-dylib/link-ordinal-multiple.rs, tests/ui/rfcs/rfc-2627-raw-dylib/link-ordinal-not-foreign-fn.rs, tests/ui/rfcs/rfc-2627-raw-dylib/link-ordinal-too-large.rs, tests/ui/rfcs/rfc-2627-raw-dylib/link-ordinal-too-many-arguments.rs, tests/ui/rfcs/rfc-2627-raw-dylib/link-ordinal-unsupported-link-kind.rs
Update the traceability matrix to have 100% everywhere again.
- warning: "untested targets: aarch64-unknown-ferrocenecoretest"
=> Update traceability matrix

ferrocene/doc/evaluation-plan/src/qualification-scope.rst
I've only mentioned the, imo, most important tools.
There are also following other tools, but I don't think we need to mention them:
* rust-gdbui
* rust-lldb
* rust-analyzer-proc-macro-srv
* llvm-tools
* llc
* llvm-ar
* llvm-cov
* llvm-dis
* llvm-nm
* llvm-objcopy
* llvm-objdump
* llvm-profdata
* llvm-readobj
* llvm-size
* llvm-strip
* opt
Fixes https://ferroussystems.clickup.com/t/8693phbdq
=> Specify that other dev tools are not qualified

ferrocene/doc/internal-procedures/src/doc-procedures.rst, src/bootstrap/src/core/builder/tests.rs, src/bootstrap/src/core/config/flags.rs, src/bootstrap/src/ferrocene/doc.rs, src/etc/completions/x.py.fish, src/etc/completions/x.py.ps1, src/etc/completions/x.py.sh, src/etc/completions/x.py.zsh
This PR adds two flags helpful when working on Sphinx extensions:
* `./x doc --fresh` ignores caches and does a fresh build of the document. I wanted to call the flag `--clean`, but that flag is already taken by bootstrap and rebuild everything including bootstrap itself.
* `./x doc --debug-sphinx` disables parallel building and shows tracebacks on exceptions.
It also documents the flags, plus `--serve` which wasn't documented before.
=> Add `./x doc --fresh --debug-sphinx` flags

ferrocene/doc/qualification-report/exts/ferrocene_test_outcomes/__init__.py, ferrocene/doc/qualification-report/exts/ferrocene_test_outcomes/render_summary.py, ferrocene/doc/qualification-report/exts/ferrocene_test_outcomes/render_template.py, ferrocene/doc/qualification-report/src/statement.rst, ferrocene/doc/qualification-report/src/tests/index.rst, ferrocene/doc/sphinx-shared-resources/exts/ferrocene_qualification/target.py, ferrocene/doc/sphinx-shared-resources/themes/ferrocene/static/ferrocene.css
This PR adds a summary table in the "test results overview" page that lists how many tests were passed for each target, and links to the more detailed page.
=> Add test results summary table

ferrocene/doc/internal-procedures/src/doc-procedures.rst, ferrocene/doc/qualification-report/src/templates/tests.jinja2, ferrocene/doc/release-notes/src/24.05.0.rst, ferrocene/doc/sphinx-shared-resources/exts/ferrocene_qualification/target.py, ferrocene/doc/sphinx-shared-resources/themes/ferrocene/static/ferrocene.css
This PR adds `:target-with-triple:`, in addition to the existing `:target:` added in #225, as per Jonathan's suggestion. It also adds documentation for both `:target:` and `:target-with-triple:` in the IP.
=> Add `:target-with-triple:` and document it

ferrocene/ci/scripts/detect-conflict-markers.py, ferrocene/tools/pull-upstream/pull.sh
#230 changed the automated pull infrastructure to attempt generating new `x.py` completions whenever pulling from upstream, which requires invoking the build system. Of course though this would fail when there are conflicts in the build system itself, and #281 was the first time that happened.
This PR changes the conflict detection script to support looking for conflicts in a subdirectory, and changes the automation to only attempt regenerating completions when no conflicts in bootstrap are detected.
=> Fix automated pull failing when conflicts are present in bootstrap

ferrocene/doc/qualification-plan/src/index.rst, ferrocene/doc/qualification-plan/src/standards/iec-61508.rst, ferrocene/doc/qualification-plan/src/standards/iso-26262.rst, ferrocene/doc/qualification-plan/src/validation.rst, ferrocene/doc/sphinx-shared-resources/themes/ferrocene/static/ferrocene.css
Before this PR, the "Validation process" page of the QP had a [Traceability Matrix](https://public-docs.ferrocene.dev/main/qualification/plan/validation.html#traceability-matrix) section mapping the standard clauses with our documents. That was hard to find and kinda misplaced in "validation process", so this PR moves this to its own top-level section, with each standard having its page:
While I was doing this, I also made some improvements:
* I converted the table from `csv-table` to a `list-table`, which is way easier to read and edit. This was done automatically, the commit message includes the command I used.
* I swapped columns so that the link to our own page is now the second column rather than the third, meaning you don't have to scroll to get to that link:
* I tweaked the IEC …
=> Rework the standards traceability section

ferrocene/doc/qualification-report/src/index.rst, ferrocene/doc/qualification-report/src/requirements-traceability.rst, ferrocene/doc/qualification-report/src/statement.rst
This adds a page to the QR explaining the traceability matrix, and lists the current exceptions.
=> Add requirements traceability page

ferrocene/doc/sphinx-shared-resources/exts/ferrocene_toctrees.py, src/bootstrap/src/ferrocene/doc.rs
This PR makes two fixes to the `--serve` command:
* Occasionally rebuilding the documentation would fail due to the `ferrocene_toctrees` extension failing to disable the builtin toctree collector. Now the extension will attempt disabling it only when it's not already disabled.
* `--fresh --serve` would not work as expected, as it'd do an initial fresh build and then incremental builds. Now all followup builds will be fresh too.
=> Bug fixes for `--serve`

ferrocene/doc/internal-procedures/src/doc-procedures.rst, src/bootstrap/src/core/builder.rs, src/bootstrap/src/ferrocene/doc.rs, src/bootstrap/src/lib.rs
This PR makes a few quality of life changes to the tooling used to build the documentation:
* There is now a new `./x doc ferrocene/doc`, which builds all the Sphinx documents at once. This is easier than manually listing all documents in the single `./x` invocation, and it's way faster than invoking `./x doc` multiple times[^1]. Bikeshedding welcome on the name, I'm not too happy about it (the only constraint is having the `ferrocene-` prefix).
* Passing `--serve` when multiple documents are requested will now print an error and exit. It was already unsupported to pass `--serve` with multiple documents, as it would only start the server for the first one, but it was a silent and unintuitive.
[^1]: When invoking `./x` to build any document, the build system first gathers the intersphinx …
=> Allow building all Sphinx docs at once, and error out if `--serve` is misused

ferrocene/doc/evaluation-plan/src/terms.rst, ferrocene/doc/evaluation-report/src/terms.rst, ferrocene/doc/glossary.rst, ferrocene/doc/internal-procedures/src/terms.rst, ferrocene/doc/qualification-plan/src/terms.rst, ferrocene/doc/qualification-report/src/terms.rst, ferrocene/doc/safety-manual/src/terms.rst
noticed that Internal Procedures had a slight difference from the rest, so decided to have this shared to avoid such in future
=> re-use the same blurb spread in glossary

ferrocene/doc/qualification-plan/src/change-tracking.rst
This PR updates the Change Tracking page to:
* Mention new changes are tracked in the release notes.
* Mention KPs are tracked in their own repository.
* Replace how we communicate about new releases and KPs to reflect the current procedures.
* Removed mention of the QMS.
=> Update change tracking page

config.example.toml, ferrocene/ci/configure.sh, src/bootstrap/src/core/config/config.rs, src/bootstrap/src/ferrocene/dist.rs, src/bootstrap/src/ferrocene/doc.rs, src/bootstrap/src/ferrocene/mod.rs
The Ferrocene channel is used to determine the overall channel of the release, by combining it with the Rust channel. Not all combinations are valid though, and some result in a bootstrap error.
Before this commit, the Ferrocene channel was read directly from the source (ferrocene/ci/channel), while the Rust channel was configured through config.toml and defaulted to "dev". This caused problems when the Ferrocene channel was not "rolling" (like in beta-24.05), as only rolling is compatible with the Rust "dev".
To address the problem, this commit moves the configuration of the Ferrocene channel to config.toml too, with a default of "rolling". This way, either the user configures both the Rust and Ferrocene channel together, or they don't configure either.
This should fix the failure in …
=> Configure the ferrocene channel through config.toml

.circleci/workflows.yml, ferrocene/doc/qualification-plan/src/ci.rst, ferrocene/doc/qualification-report/exts/ferrocene_test_outcomes/outcomes.py, ferrocene/doc/qualification-report/src/statement.rst, ferrocene/doc/qualification-report/src/templates/tests.jinja2, src/bootstrap/src/core/build_steps/test.rs, src/bootstrap/src/core/builder/tests.rs, src/bootstrap/src/core/config/flags.rs, src/bootstrap/src/ferrocene/doc.rs, src/etc/completions/x.py.fish, src/etc/completions/x.py.ps1, src/etc/completions/x.py.sh, src/etc/completions/x.py.zsh
This PR makes multiple changes to the test outcomes pages:
* The blurb about bare metal targets has been moved to the qualification plan, since it will be shared by multiple targets in the future, and on the report there is now a link to it.
* Unified the wording for tests always passing and tests only executed on hosts.
* Noted that tidy and linkchecker are only executed on hosts, rather than all targets.
* Switched to a table to display compiletest outcomes.
* Switched to a table to display cargo test outcomes.
* Moved the KP statement to the statement page, rather than duplicating it for each target.
* Removed the note around stages, as we don't expose them anymore.
* Changes CI to emit separate metrics for each crate.
=> More improvements to the test outcomes pages

ferrocene/doc/user-manual/src/install.rst, ferrocene/doc/user-manual/src/targets/aarch64-unknown-none.rst, ferrocene/doc/user-manual/src/targets/x86_64-unknown-linux-gnu.rst
This PR reworks the installation instructions with the new installation method, using releases.ferrocene.dev to download binaries and the new tarball naming scheme (to be implemented). It also adds the list of which packages to install in the user manual.
This is half of https://app.clickup.com/t/8693phhyj
=> Rework installation instructions with the updated content

ferrocene/doc/safety-manual/src/procedures.rst
Fixes https://ferroussystems.clickup.com/t/8693tyea2.
Is `ref:` the correct way to link to a section on a page?
=> Update linker requirements

ferrocene/ci/scripts/calculate-release-job-matrix.py, ferrocene/ci/scripts/run-self-test.sh, src/bootstrap/src/ferrocene/dist.rs, src/bootstrap/src/utils/tarball.rs
This PR implements the new tarball naming scheme agreed in https://designs.ferrocene.dev/tarball-names.html. It also bumps the metadata version from 3 to 4, so that the release process can identify which naming scheme to use.
=> Use the new tarball naming scheme

ferrocene/ci/scripts/prepare-docs-to-github-pages.py
Here is what I get for not testing things locally. A newline was added in the tarball name, which, uh, didn't work.
=> Actually fix github pages publishing

.circleci/workflows.yml
https://github.com/ferrocene/ferrocene/pull/361 got hit by the brownout in https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177. This PR updates the CircleCI images to the latest available ones.
=> Bump CircleCI images

ferrocene/ci/scripts/calculate-release-job-matrix.py
This PR makes four major changes to the release scheduling code:
* Adds easier support for local testing, as explained in the comment at the top of the file.
* Drops support for metadata version 2, which is not supported by publish-release anymore.
* Changed the script to gracefully handle unknown metadata version: commits with unknown metadata will be skipped.
* During scheduled releases (not manual ones) the script will now check the latest released commit for each release, and skip it if it's the same as the commit we're trying to publish. Publishing duplicate releases is already catched and blocked by publish-release, but it would result in a build failure. Hopefully this change will make the Actions page be less red.
=> Release scheduling changes

src/bootstrap/src/utils/tarball.rs
While noodling with how CI tasks are split up locally I bumped into a documentation lint which caused this command (which the CI runs) to fail:
```bash
./x.py --stage 2 dist $(ferrocene/ci/split-tasks.py dist)
```
Here is a snippet of the relevant output:
```bash
Documenting stage2 bootstrap (x86_64-unknown-linux-gnu)
Checking build_helper v0.1.0 (/home/ana/git/ferrocene/ferrocene/src/tools/build_helper)
Documenting bootstrap v0.0.0 (/home/ana/git/ferrocene/ferrocene/src/bootstrap)
error: this URL is not a hyperlink
--> src/utils/tarball.rs:306:13
|
306 |     /// See https://designs.ferrocene.dev/tarball-names.html
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://designs.ferrocene.dev/tarball-names.html>`
|
= note: bare URLs are …
```
=> Fixup doc lint in the dist task

ferrocene/ci/scripts/persist-between-jobs.sh
Plucked from https://github.com/ferrocene/ferrocene/pull/283, this fixes the "Invocation Stacking" issue in the generated reports from CI.
=> Properly exclude `build-metrics.json` from Tar

.circleci/workflows.yml, ferrocene/ci/split-tasks.py
Right now the `x86_64-linux-dist` task takes about 21 minutes. We'd like that to take less time!
The next fastest job (aarch64-linux-compile) is about 17 minutes, so we could in theory shave up 4 minutes off the CI just modifying this one job.
Reviewing the 'Resource utilization report' uncovered that we were building a few tools:
* `clippy` at ~7s + ~129s = ~136s:
* `rustfmt` at ~7s + ~70s = ~77s:
* `rust-analyzer` at ~14s + ~184s = ~198s
Since each of these are fairly independent tasks, we could extract them into an independent runner.
I split those out into a `dist:tools` job.
During my experimenting we also noticed the `rustc-docs` task could set to `None`.
I created a very rudimentary script.
<details>
<summary>Script</summary>
```fish
#!/usr/bin/fish
argparse 't/tools' 'f/folder=' …
```
=> Split up dist tasks a bit more

.circleci/workflows.yml
Embarassingly, https://github.com/ferrocene/ferrocene/pull/372 had a bug. https://github.com/ferrocene/ferrocene/pull/372#discussion_r1517420354 suggests a solution. This PR follows that.
=> Make dist-tools task a dep of the self-test task

ferrocene/doc/release-notes/src/24.05.0.rst, ferrocene/doc/release-notes/src/conf.py, ferrocene/doc/release-notes/src/index.rst, ferrocene/doc/release-notes/src/terms.rst
It had a typo, but I also found it more complex than it needed to be
=> make "additional tools" release note more simple

.github/workflows/automation-pull-upstream.yml, ferrocene/tools/pull-upstream/pull.sh
This allows to customize how many PRs are included in pulls from upstream when manually starting the workflow.
=> Allow configuring the max number of PRs in pulls from upstream

.circleci/workflows.yml, ferrocene/ci/docker-images/ubuntu-20/Dockerfile, ferrocene/doc/release-notes/src/next.rst, ferrocene/doc/target-names.toml, ferrocene/doc/user-manual/src/targets/index.rst, ferrocene/packages.toml
Adds an experimental `armv8r-none-eabihf` which is untested.
=> Add experimental armv8r-none-eabihf target

.github/workflows/release.yml
This should remove the last reason why the release job is red with no actual failure. It currently happens on weekends when there are no new releases to publish.
=> Prevent the release job from failing when no release should be published

ferrocene/doc/sphinx-shared-resources/exts/ferrocene_qualification/__init__.py, ferrocene/doc/sphinx-shared-resources/exts/ferrocene_qualification/substitutions.py, ferrocene/doc/user-manual/src/install.rst, src/bootstrap/src/ferrocene/doc.rs
Turns out we can't inject the channel name in our documentation! Our document signature scheme depends on the content of the signature not to change between the beta and stable branch (as we need to keep the same document IDs and signatures between the two), while injecting the channel implies the signatures would be invalidated.
Figured this out while signing documents with Florian.
=> Remove channel sphinx substitution

src/bootstrap/src/ferrocene/sign.rs
Sigstore updated their TUF root in a way that is not compatible with cosign 2.2.3 anymore. See https://blog.sigstore.dev/tuf-root-update/ for more information. This PR bumps the pinned version of cosign we use.
=> Bump to cosign 2.2.3

Cargo.lock, ferrocene/tools/self-test/Cargo.toml, ferrocene/tools/self-test/src/binaries.rs, ferrocene/tools/self-test/src/compile.rs, ferrocene/tools/self-test/src/env.rs, ferrocene/tools/self-test/src/error.rs, ferrocene/tools/self-test/src/linkers.rs, ferrocene/tools/self-test/src/linkers/argparse.rs, ferrocene/tools/self-test/src/main.rs, ferrocene/tools/self-test/src/test_utils.rs, ferrocene/tools/self-test/src/utils.rs
Apart from some small cleanups, the highlights of this refactor are:
- Combining all environment variable related stuff in the `env` module.
- Using `thiserror` to save 50+ lines of code.
- ~~Use `pub` instead of `pub(crate)`, because that's the same in binary crates.~~
=> Refactor `ferrocene-self-test` more

config.example.toml
I think adding public doc link to the key section in example config is good but please correct me if I am mistaken.
=> Minor - doc: add aws-profile key to to config.example.toml

ferrocene/ci/split-tasks.py
This PR
- adds type hints to most functions
- refactors `find_all_compiletests` a bit
**Question:** `find_all_compiletests` is written rather generically, but I only see it called one time in the whole repository? Why is it written like that? If it does not need to be that generic we can also change the types of the arguments to be not `None`.
=> Refactor `ferrocene/ci/split-tasks.py`

.github/workflows/automation-backport.yml, .github/workflows/automation-pull-subtrees.yml, .github/workflows/automation-pull-upstream.yml, .github/workflows/automation-update-lockfiles.yml, .github/workflows/backport-labels.yml, .github/workflows/docs-to-github-pages.yml, .github/workflows/release.yml, ferrocene/doc/sphinx-shared-resources/.github/workflows/ci.yml
This should silence the warning:
=> CI: Update `actions/checkout` to `v4`

ferrocene/tools/self-test/src/targets.rs
This adds `armv8r-none-eabihf`, `thumbv7em-none-eabihf`, and `thumbv7em-none-eabi` to `ferrocene-self-test`'s checks.
It avoids `wasm32-unknown-unknown` at this time as it is uncompatible with current methodology:
```bash
❯ ./ferrocene-self-test
Info: using sysroot /tmp/tmp.jJc1x3RaAO/sysroot
Success: binary rustc is valid
Success: binary rustdoc is valid
Success: binary cargo is valid
Success: target installed correctly: x86_64-unknown-linux-gnu
Success: target installed correctly: aarch64-unknown-linux-gnu
Success: target installed correctly: aarch64-unknown-none
Success: target installed correctly: armv8r-none-eabihf
Success: target installed correctly: thumbv7em-none-eabihf
Success: target installed correctly: thumbv7em-none-eabi
Success: target installed correctly: …
```
=> Add some missing targets to self-test

src/bootstrap/src/core/build_steps/dist.rs, src/bootstrap/src/ferrocene/dist.rs
adds proxy symlink to the following:
- rust-gdb
- rust-gdbgui
- rust-lldb
- clippy-driver
- cargo-clippy
- rustfmt
- cargo-fmt
- ferrocene-self-test
To test: 
- Run the full build using `bors try`.
- Then fetch the tarballs from the run's aws s3 bucket
- Untar and check the JSON files in `share/criticaltrust/ferrocene/` 
- The right binaries should have `needs-proxy: true` in the `signed` section/key
Ticket: 86944n9mwhe
=> adds missing proxied binaries to the tarball list

.github/dependabot.yml
Taken from https://stackoverflow.com/a/75078947.
The configuration[^1] seems to make sense, but I am unsure how to test it.
I also considered to set the update interval to to "weekly", since `flip-link` only receives updates rarely. But I want dependabot to pick up the update within a day _when_ we publish a new version.
[^1]: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
=> Check for `flip-link` updates every day

ferrocene/ci/scripts/mirror-sphinx-shared-resources.py
`str.lstrip` is too hungry[^1], therefore `str.removeprefix`[^2] will take over from now on and hopefully behave better.
`str.removeprefix` is new in Python 3.9, which is okay since the GitHub Actions Runner contains Python 3.10[^3].
[^1]: It ate a leading `e` of a commit hash 😱 
[^2]: https://docs.python.org/3/library/stdtypes.html#str.removeprefix
[^3]: https://github.com/actions/runner-images/blob/069e7c963c42992e601f64880bccd98681b953dc/images/ubuntu/Ubuntu2204-Readme.md?plain=1#L27
=> Fix "last commit detection" in mirror-sphinx-shared-resources automation

ferrocene/doc/user-manual/src/using-compiler/executable.rst, ferrocene/doc/user-manual/src/using-compiler/file-formats.rst, ferrocene/doc/user-manual/src/using-compiler/library.rst
- This could lead people to think the behavior is different from upstream.
- "rustc" is short for Rust compiler... we need not add another "compiler"
=> avoid confusion and simplify

ferrocene/tools/self-test/src/compile.rs, ferrocene/tools/self-test/src/targets.rs, ferrocene/tools/self-test/src/test_utils.rs, ferrocene/tools/self-test/src/test_utils/bin_builder.rs
Changes
- move BinBuilder to own module
- reduce repetition in target tests
- use `TestUtils` in `test_find_libraries_in`
- some drive-by changes
- please double check the binary condition in `extract_library_name` is still correct (I inverted it to simplify the code)
=> Refactor `ferrocene-self-test`

src/bootstrap/src/ferrocene/dist.rs
A recent-ish change in bootstrap (not sure exactly which PR) started requiring the .gitmodules file to be included in the source tarball, otherwise bootstrap will not start.
The upstream source tarball does include that file, so this commit replicates the change in Ferrocene too.
=> Include `.gitmodules` in the source tarball

src/bootstrap/src/core/builder.rs
This PR backports https://github.com/rust-lang/rust/pull/119582 to 1.76, allowing to build Ferrocene 24.05 with vendored dependencies.
=> Handle vendored sources when remapping paths

src/bootstrap/src/core/builder.rs, src/bootstrap/src/ferrocene/dist.rs
This PR improves vendoring of dependencies in the source tarball by:
* Vendoring dependencies for `cargo` and `rustc_codegen_gcc` too, which are outside of the workspace.
* Using the correct path when remapping vendored dependencies, as we store our vendored crates in `vendor/rust` rather than just `vendor` (to support vendoring of other languages in the future).
* Passes `--versioned-dirs` to match upstream.
=> Improve vendoring

Cargo.lock, ferrocene/tools/document-signatures/Cargo.toml, ferrocene/tools/generate-tarball/Cargo.toml, ferrocene/tools/self-test/Cargo.toml, ferrocene/tools/traceability-matrix/Cargo.toml
These are either internal tools,
or are to be distributed with the toolchain itself.
=> remove versioning from ferrocene tools

ferrocene/tools/traceability-matrix/README.md, ferrocene/tools/traceability-matrix/src/annotations.rs, ferrocene/tools/traceability-matrix/src/documentations.rs, ferrocene/tools/traceability-matrix/src/main.rs, ferrocene/tools/traceability-matrix/src/matrix.rs, ferrocene/tools/traceability-matrix/src/report.rs, ferrocene/tools/traceability-matrix/src/test_outcomes.rs, src/bootstrap/src/core/builder.rs
Noteable changes:
- Add README
- Use `anyhow::Result<T>` instead of `Result<T, anyhow::Error>` (it's shorter and saves the import)
- Document some functions (want to document more)
- Add `TraceabilityMatrix::analyze_document`
- Add `TestOutcome::insert`
=> Refactor `tools/ferrocene/traceability-matrix`

ferrocene/ci/scripts/llvm-cache.sh
`sha256sum` is not a valid binary on Mac, and appears to have been silently failing.
This is causing the llvm cache to not be used and adding ~20 mins to most Mac workflows.
```
$ sha256sum
Error: nu::shell::external_command
× External command failed
╭─[entry #1:1:1]
1 │ sha256sum
· ────┬────
·     ╰── executable was not found
╰────
help: No such file or directory (os error 2)
Exit status 1
$ shasum -a 256
asdasd^D
61b4c705859f4158d38090c1e38e8fdc4f3d29db007f012766276aa498835cf6  -
```
https://app.circleci.com/pipelines/github/ferrocene/ferrocene/3574/workflows/9f9f9a89-56a2-4074-bb18-ef5b7a29fa9f/jobs/17241
=> Use a compatible shasum for Mac

ferrocene/doc/evaluation-report/src/tool-analysis.rst, ferrocene/doc/glossary.rst, ferrocene/doc/index/index.html, ferrocene/doc/release-notes/src/24.05.0.rst, ferrocene/doc/sphinx-substitutions.toml, ferrocene/doc/user-manual/src/cli.rst
This PR addresses the feedback we got from TÜV on the 24.05.0 release:
* Replaces "TQL T3" with "class T3", and removes TQL from the glossary.
* Restricts the use of the `--crate-type` flag to prevent generating dynamic libraries, as our documents don't yet cover the use of dynamic libraries.
=> Address feedback from TÜV

ferrocene/ci/split-tasks.py, src/bootstrap/src/core/build_steps/dist.rs, src/bootstrap/src/core/build_steps/doc.rs, src/bootstrap/src/core/builder/tests.rs
Before this PR, whenever we needed to exclude a step from CI because it didn't make sense for Ferrocene, we changed the split-tasks script to always `--exclude` it. That was a fine approach for CI, as the script controlled what we executed.
We have customers building from source now though, and they don't use the script (nor should they). This PR thus moves to a different way of permanently excluding those jobs: changing bootstrap to prevent executing the jobs at all.
=> Prevent excluded steps from being executed at all

.circleci/calculate-parameters.py, .circleci/workflows.yml
Remove a potential footgun where we forget to self-test on a target.
This change will also be relevant to https://github.com/ferrocene/ferrocene/pull/544, since that causes our host platform support to diverge in new and interesting ways.
=> Lift the repeated FERROCENE_TARGETS bits into a workflow parameter

ferrocene/doc/sphinx-shared-resources/requirements.in, ferrocene/doc/sphinx-shared-resources/requirements.txt, ferrocene/doc/sphinx-shared-resources/themes/ferrocene/theme.toml
This PR updates to the latest Sphinx version, which includes https://github.com/sphinx-doc/sphinx/pull/11665. Along with it I also updated the rest of the dependencies, and replaced `theme.conf` with `theme.toml`.
=> Update to the latest Sphinx version

src/bootstrap/src/core/build_steps/doc.rs, src/tools/linkchecker/main.rs
The documentation index page right now is showing upstream's index page, which is not what we want. To work around that, this PR changes that step to panic when trying to execute it, and disables another step that calls it.
=> Fix documentation index page

.circleci/workflows.yml
The macOS self test job might be executed slightly before the Linux cross-compilation targets get built. This causes spurious failures like we saw in https://github.com/ferrocene/ferrocene/pull/593.
cc @Hoverbear we want to do the same for the Windows PR
=> Require Linux targets for the macOS self-test job

ferrocene/ci/scripts/run-self-test.sh, ferrocene/tools/self-test/src/error.rs
While trying to debug a self-test failure in #595 I noticed two complicating issues:
* A cleanup of downloaded artifacts was always performed, meaning it was not possible to inspect a failed state.
* Command failures did not include `stderr`, making it very difficult to discern the source of the problem without reproducing the state manually (cleanup also happens here)
This PR:
* Adds `COMMIT="..."` so we can tell the script which commit to test against if we want.
* Adds `SKIP_CLEANUP=true` so we tell the script not to clean up downloaded artifacts.
=> Make self-test easier to debug

ferrocene/ci/scripts/llvm-cache.sh
We store our LLVM caches in a specific S3 bucket location. This PR ensures we log the location, it also ensures we log both when we start, and when we complete, both actions. (Previously we only logged starting storing the cache, and after restoring)
This fell mostly out of #565.
=> Make llvm-cache.sh log more useful and verbose information

ferrocene/doc/user-manual/src/index.rst, ferrocene/doc/user-manual/src/rustc/cli.rst, ferrocene/doc/user-manual/src/rustfmt/cli.rst, ferrocene/doc/user-manual/src/rustfmt/install.rst, ferrocene/doc/user-manual/src/rustfmt/usage.rst, ferrocene/doc/user-manual/src/targets/x86_64-unknown-linux-gnu.rst
This PR adds `rustfmt` to the user manual. Added sections are:
- installation
- usage
- command-line interface _(this section is bare bones atm and will be extended in a follow-up PR)_.
Are any sections missing?
=> Write `rustfmt` user manual

.gitmodules
An upstream change resulted in a conflict,
due to https://github.com/rust-lang/rust/pull/125166.
=> move submodule entry to a place where it will not conflict

ferrocene/doc/index/index.html
We forgot to include the CSS file that shows the technical report link if the users have the signatures subset in their documentation. This has to be backported to 24.05.0.
=> Allow showing the technical report in the stable channel

ferrocene/ci/scripts/calculate-release-job-matrix.py
In https://github.com/ferrocene/publish-release/pull/51 we introduced channel metadata v3, to store the full list of releases rather than just the last release. This PR adds support for it in the release matrix calculation.
Also, it fixes two unrelated problems I discovered while developing this.
=> Fix release scheduler to account for channel metadata v3

ferrocene/tools/generate-tarball/src/generator.rs, ferrocene/tools/generate-tarball/src/signatures.rs, src/bootstrap/src/utils/tarball.rs
I noticed that some of the manifests in the produced packages did not have `needs-proxy` set correctly. This should fix that.
=> Fix needs_proxy detection on Windows

.circleci/calculate-parameters.py
This PR
- mostly adds type hints so that I get information about the variables and functions when hovering over them
- replaces deprecated `.utcnow()`
- in `calcualte_paramameters`, I switched from `target +=` to `target =`, because iiuc exactly one case will always match.
- sort imports alphabetically :smile:
---
PS. I also wanted to find a type for the global `s3` and `ecr` variable, but unfortunately I could not https://github.com/ferrocene/ferrocene/blob/a5a6acb2f0c1f84468c82c760c83d5a883a56a9e/.circleci/calculate-parameters.py#L58-L59
Python reports `botocore.client.S3` and `botocore.client.ECR`, but I am unable to import that:
```python
>>> import boto3
>>> type(boto3.client("s3", region_name="us-east-1"))
<class 'botocore.client.S3'>
>>> from botocore.client import S3
Traceback …
```
=> Refactor `.circleci/calculate-parameters.py`

ferrocene/ci/configure.sh
This PR changes the configure script to better take `OUTSIDE_FERROUS=1` into account:
* It now prevents including the technical report, as it is hosted in AWS.
* It now disables including document signatures, as that requires AWS access.
=> Improve `OUTSIDE_FERROUS=1` when configuring

ferrocene/ci/scripts/llvm-cache.sh
@tshepang's sharp eye noticed this. :)
Eg of the tempfiole on windows:
```
dc8ef67ed19367be8fd39e5b0dad9e2786f689d70e2ec1759e5a677f57a42ea6 *ferrocene/ci/docker-images/ubuntu-20/Dockerfile
efca746f02c4fdadc95c44341d528b92ff7fe94e6bc1ca34f0c53b06f9c2c944 *ferrocene/ci/docker-images/ubuntu-20/reuse-requirements.txt
f6b6e44fadcee8e16cf14f8e69016777b3952a5af9b3e66acf74fae08a958fa9 *ferrocene/ci/docker-images/ubuntu-20/sudoers
a8620cc38d451cceb5c62c808d0fb47456ead11ef590731862adfef62df71a2e *ferrocene/ci/docker-images/ubuntu-23/Dockerfile
efca746f02c4fdadc95c44341d528b92ff7fe94e6bc1ca34f0c53b06f9c2c944 *ferrocene/ci/docker-images/ubuntu-23/reuse-requirements.txt
f0782d7254d0a6303995b50936b788e6ddc97e037ba33f0ca290ff0d9eb9418f *src/bootstrap/Cargo.lock …
```
=> `llvm-cache s3-url` outputting the same on Windows and Linux

ferrocene/doc/user-manual/src/index.rst, ferrocene/doc/user-manual/src/targets/index.rst, ferrocene/doc/user-manual/src/targets/x86_64-pc-windows-msvc.rst
MSVC Windows on x86_64 needs some prerequisites. This PR adds those prerequisites.
- Adds a new page for MSVC Windows on x86_64.
- Links to that page from targets page's Experiemental targets section.
=> Installation docs for x86_64-pc-windows-msvc

ferrocene/tools/generate-tarball/src/compression.rs, ferrocene/tools/generate-tarball/src/tarballer.rs, src/bootstrap/src/core/builder.rs, src/bootstrap/src/ferrocene/dist.rs, src/bootstrap/src/ferrocene/install.rs, src/bootstrap/src/ferrocene/mod.rs
@pietroalbini noticed that `x.py install` was broken due to some of the changes we'd made.
This is largely due to us packaging our tarballs slightly differently and not generating an `install.sh`.
This PR creates a new ferrocene specific install step for each package that directly renames the tarball outputs to their configured destinations.
It supports all the `config.toml` options as well as `DESTDIR`.
=> Fix `x.py install`

tests/ui/ferrocene/compiler-arguments/target/target_invalid.rs, tests/ui/ferrocene/compiler-arguments/target/target_not-available.rs
The output of these two tests does not contain any host specific strings, so there is no reason not to run these only on one target.
=> Enable 2 of 3 compiler-arguments target tests on all architectures

ferrocene/doc/user-manual/src/index.rst, ferrocene/doc/user-manual/src/targets/aarch64-apple-darwin.rst, ferrocene/doc/user-manual/src/targets/index.rst
Similar to #664, but Apple flavored instead of glass-flavored.
=> Installation docs for aarch64-apple-darwin

src/bootstrap/download-ci-llvm-stamp
Following changes in:
https://github.com/rust-lang/rust/pull/125141
in [ff25b24](https://github.com/ferrocene/ferrocene/pull/691/commits/ff25b24a10ffcf10ae0dcddea60710cf4c12cbb5), only upstream download configuration was changed.
=> Update stamp following this change

tests/ui/ferrocene/compiler-arguments/target/target.rs
Allows enabling the remaining target test after https://github.com/ferrocene/ferrocene/pull/679
=> Enable compiler-arguments/target test on all platforms

ferrocene/library/libc/src/lib.rs
https://github.com/rust-lang/libc/blame/libc-0.2/src/lib.rs
(this contains a duplicate of `dead_code` that we will remove later)
=> attempt to circumvent libc failure

ferrocene/doc/evaluation-report/src/rustc/tool-analysis.rst
I am uncertain if detectability is set correct for all potential errors. Please review carefully.
My thinking was that everything input related can be reviewed since it is clear what options there are and is therefore detectable. Everything internal or output related is not detectable, because it is unclear what should be emitted/generated.
=> `rustc` tool analysis: add detectable column

src/bootstrap/src/ferrocene/doc.rs
Serving multiple docs at the same time is not supported by the build system, since we can only have one server running at the time. To enforce that, there is a check in bootstrap ensuring the `builder.should_serve()` function is only called once.
A previous refactor broke the flag though, because it resulted in the `builder.should_serve()` method being called by all `objects.inv` gathering steps in addition to the html building step. This PR fixes the problem.
=> Only try serving the docs when building html docs

ferrocene/doc/safety-manual/src/environment.rst
This is required by ISO 26262 part 8 clause 11.4.4.1.a, which links to the environment page in our [standard traceability page](https://public-docs.ferrocene.dev/main/qualification/plan/standards/iso-26262.html). I discovered we are not doing that during a routine reading of the documents.
For now this fix just targets the next 24.08 release, I'll send a larger refactoring to the main branch in a followup PR.
=> [1.79] Add Ferrocene and Rust version to the Safety Manual

ferrocene/doc/sphinx-shared-resources/exts/ferrocene_domain_cli/__init__.py, ferrocene/doc/sphinx-shared-resources/exts/ferrocene_domain_cli/domain.py, ferrocene/doc/sphinx-shared-resources/exts/ferrocene_domain_cli/traceability_ids.py, ferrocene/doc/user-manual/src/rustfmt/cli.rst
We do not want to (i.e. need to) test the cli options of `rustfmt`, therefore this PR allows disabling the generation of entries in the traceability matrix. It also sets the flag for the rustfmt cli.
Before there was a red "UM: rustfmt Command-Line Interface" entry. After this PR it will be gone.
Before: ![Screenshot from 2024-07-05 13-10-06](https://github.com/ferrocene/ferrocene/assets/37087391/7490d85a-99c3-4acc-b06e-b76e0d5db477)
After: ![Screenshot from 2024-07-05 13-10-20](https://github.com/ferrocene/ferrocene/assets/37087391/3bb81920-cd64-48f5-bac2-89d4bf592d60)
=> Add `no_traceability_matrix` flag to `cli:program` directive

ferrocene/doc/release-notes/src/24.08.0.rst, ferrocene/doc/release-notes/src/index.rst, ferrocene/doc/release-notes/src/next.rst
Will *manually* backport them to the 24.08 beta branch later.
=> Add Ferrocene 24.08 release notes

ferrocene/doc/specification/exts/ferrocene_spec/__init__.py, ferrocene/doc/specification/exts/ferrocene_spec/definitions/__init__.py, ferrocene/doc/specification/exts/ferrocene_spec/sphinx_fixes.py, ferrocene/doc/specification/src/attributes.rst, ferrocene/doc/specification/src/changelog.rst, ferrocene/doc/specification/src/conf.py, ferrocene/doc/specification/src/entities-and-resolution.rst, ferrocene/doc/specification/src/expressions.rst, ferrocene/doc/specification/src/functions.rst, ferrocene/doc/specification/src/general.rst, ferrocene/doc/specification/src/generics.rst, ferrocene/doc/specification/src/glossary.rst, ferrocene/doc/specification/src/index.rst, ferrocene/doc/specification/src/ownership-and-deconstruction.rst, ferrocene/doc/specification/src/program-structure-and-compilation.rst, ferrocene/doc/specification/src/types-and-traits.rst
This PR updates the specification subtree, and in the last commit it replaces the release notes link with Ferrocene's, rather than upstream's.
=> Bump specification

ferrocene/doc/release-notes/src/24.05.0.rst, ferrocene/doc/release-notes/src/24.08.0.rst, ferrocene/doc/release-notes/src/index.rst, ferrocene/doc/release-notes/src/next.rst
This PR backports the release notes in the main branch to 24.08, and removes the upcoming mark *just in that branch*.
=> [1.79] Backport release notes to 24.08.0

ferrocene/doc/qualification-plan/src/details.rst
Slightly expand the descriptions of THIR and MIR lowering to not be a single sentence. Indicate that THIR lowering is fairly simple and MIR lowering is complex.
Documentation only change.
=> qual-plan/details: expand short descriptions

ferrocene/doc/internal-procedures/src/external-contributions.rst, ferrocene/doc/internal-procedures/src/index.rst
I am unsure if the Qualification Plan (QP) is the right place to document this? Initially I thought about the Internal procedures, but they just link to the QP for the Product engineering procedures.
=> Document how to run CI for external contributions

ferrocene/doc/release-notes/exts/ferrocene_relnotes/rust_changelog.py
We fixed this problem on [`stable`](https://app.circleci.com/pipelines/github/ferrocene/ferrocene/5702/workflows/e01f0678-fe43-43f2-8619-7c19a76f3ce4/jobs/30201?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) when the SemVer version is not correct.
Same fix for main.
=> fix for incompatible SemVer

ferrocene/doc/document-list/exts/ferrocene_document_list.py, ferrocene/doc/qualification-report/exts/ferrocene_test_outcomes/outcomes.py, ferrocene/doc/qualification-report/exts/ferrocene_test_outcomes/render_template.py, ferrocene/doc/release-notes/exts/ferrocene_relnotes/rust_changelog.py, ferrocene/doc/sphinx-shared-resources/exts/ferrocene_qualification/signature_page.py, src/bootstrap/src/ferrocene/doc.rs
Canonicalizing paths yields [extended length paths](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) on windows causing the paths to differ significantly if one of the two doesn't exist. From what I can tell we mainly want to get rid of any potential `..` and `.` segments from the paths though (and make them absolute), not resolve symlinks, so absolutizing should suffice.
Additionally this sets the encoding for text file `open` calls to `utf8` as that defaults to `cp1252` on windows.
=> Allow building ferrocene docs on windows

ferrocene/doc/internal-procedures/src/upstream-pulls.rst
This quick PR adds the manual updates needed when `tidy check` fails complaining about the missing license.
=> Document Tidy failure

compiler/rustc_mir_transform/src/jump_threading.rs, ferrocene/doc/document-list/signature/signature.toml, ferrocene/doc/release-notes/src/24.08.0.rst, tests/mir-opt/jump_threading.floats.JumpThreading.panic-abort.diff, tests/mir-opt/jump_threading.floats.JumpThreading.panic-unwind.diff, tests/mir-opt/jump_threading.rs
Jump threading stores values as `u128` (`ScalarInt`) and does its comparisons for equality as integer comparisons.
This works great for integers. Sadly, not everything is an integer.
Floats famously have wonky equality semantcs, with `NaN!=NaN` and `0.0 == -0.0`. This does not match our beautiful integer bitpattern equality and therefore causes things to go horribly wrong.
While jump threading could be extended to support floats by remembering that they're floats in the value state and handling them properly, it's signficantly easier to just disable it for now.
Ferrocene-backport-of: rust-lang/rust#128271
=> Disable jump threading of float equality

ferrocene/tools/pull-subtrees/subtrees.yml
in the next automation run
the latest version of backtrace-rs fixes backtrace related UI tests for the QNX targets
=> add rust-lang/backtrace-rs subtree

ferrocene/doc/qualification-report/src/requirements-traceability.rst
If https://github.com/ferrocene/ferrocene/pull/842 lands, the two tests are in fact green in the matrix
=> Remove stale exceptions from requirements-traceability

ferrocene/doc/release-notes/src/24.08.0.rst
Ran this command to copy all the changes we made to the 24.08.0 release notes:
```
git checkout origin/release/1.79 -- ferrocene/doc/release-notes/src/24.08.0.rst
```
=> Update release notes for 24.08.0

.github/workflows/automation-backport.yml, .github/workflows/automation-pull-subtrees.yml, .github/workflows/automation-pull-upstream.yml, .github/workflows/mirror-sphinx-shared-resources.yml, ferrocene/ci/scripts/github_app_auth.py
This kinda fell out of some work with #876 #867 and just brings the `gha-app-auth.py` script into the fold so other scripts can call it.
=> Move `gha-app-auth.py` to scripts as `gha_app_auth.py`

ferrocene/tools/pull-subtrees/pull.py, ferrocene/tools/pull-subtrees/subtrees.yml, ferrocene/tools/pull-upstream/pull.sh, library/Cargo.lock, src/tools/tidy/src/deps.rs
There is no reason for us to currently constantly updating all entries in this lock file to their latest semver release. This can create unnecessary problems and the only entry in the lockfile that is relevant for us to keep up to date is the one for our subtree(s), so we should only be updating that one such that it is always in sync with the subtree version number.
This PR resets our `library/Cargo.lock` back to upstream to remove divergence there
=> Only update `library/Cargo.lock` in subtree pulls

.github/workflows/automation-pull-subtrees.yml
```
Traceback (most recent call last):
File "/home/runner/work/ferrocene/ferrocene/ferrocene/tools/pull-subtrees/pull.py", line 442, in <module>
PullSubtreePR(subtree, args.target).create()
File "/home/runner/work/ferrocene/ferrocene/ferrocene/tools/pull-subtrees/../common/automated_prs.py", line 62, in create
result = self.run()
File "/home/runner/work/ferrocene/ferrocene/ferrocene/tools/pull-subtrees/pull.py", line 322, in run
self.diff = update_subtree(self.repo_root, self.subtree)
File "/home/runner/work/ferrocene/ferrocene/ferrocene/tools/pull-subtrees/pull.py", line 252, in update_subtree
AFTER_ACTIONS[action[0]](subtree, repo_root, action[1:])
File "/home/runner/work/ferrocene/ferrocene/ferrocene/tools/pull-subtrees/pull.py", line 275, in action_update_cargo_lock
for [package_name, …
```
=> we use a method introduced in Python 3.12

.github/workflows/automation-backport.yml, .github/workflows/automation-pull-subtrees.yml, .github/workflows/automation-pull-upstream.yml, ferrocene/ci/scripts/github_app_auth.py, ferrocene/tools/pull-subtrees/pull.py, ferrocene/tools/pull-upstream/create-release-branch.sh
After migrating CI checks to GitHub Actions, it was discovered that automated PRs do not trigger CI anymore. This is because GitHub Actions refuses to start any workflow on commits pushed by a GitHub Action's `$GITHUB_TOKEN`, to prevent infinite loops. Still, we do want CI to run on those commits, so we have to resort to using our own GitHub App token.
This PR does that by creating a new `automations` environment containing a GitHub App with write access to this repository's contents, and adding a `--set-git-credentials` flag to `github_app_auth.py` to configure git to use the newly created token.
It also cleans up the existing separate GitHub apps that automations had:
* The app for `automation-backport` didn't seem to be used anywhere.
* The app for `automation-pull-subtrees` was only …
=> Fix automation commits not triggering CI

ferrocene/ci/run.sh, ferrocene/ci/split-tasks.py
After chatting with the team some folks expressed desire to improve the insight into what exactly the CI is running when `run.sh` or `split-tasks.py` is run.
This adds a bit of echo (like `set -x` but more limited) so folks can know what's going on.
=> Split tasks and run.sh output what they're running

.github/workflows/automation-backport.yml, .github/workflows/automation-pull-subtrees.yml, .github/workflows/automation-pull-upstream.yml
I noticed some of our automations aren't having their PRs triggered on pushes. This makes those scripts use the app token instead of the normal Github token context.
=> Use Github token from app_auth

.circleci/workflows.yml, ferrocene/doc/internal-procedures/src/partners/qnx.rst, ferrocene/doc/qualification-report/src/index.rst, ferrocene/doc/qualification-report/src/rustc/aarch64-unknown-nto-qnx710.rst, ferrocene/doc/qualification-report/src/rustc/x86_64-pc-nto-qnx710.rst, ferrocene/doc/release-notes/src/next.rst, ferrocene/doc/safety-manual/src/scope.rst, ferrocene/doc/user-manual/src/targets/aarch64-unknown-nto-qnx710.rst, ferrocene/doc/user-manual/src/targets/index.rst, ferrocene/doc/user-manual/src/targets/x86_64-pc-nto-qnx710.rst
Write the qualification docs for QNX. We only qualify with a specific QNX version for now.
Review:
```bash
./x.py doc ferrocene/doc/qualification-report --fresh
./x.py doc ferrocene/doc/safety-manual --fresh
./x.py doc ferrocene/doc/user-manual --fresh
```
=> Add QNX to qualification report

library/std/src/sys/pal/unix/process/process_common/tests.rs
these probably were left behind after some rebase went amiss
=> qnx: remove leftover `ignore` attributes

library/std/src/error/tests.rs, tests/ui/error-with-backtrace-outputs-correctly.rs
to work around an issue where the `std::error` API hits an OOM condition when used from a thread
=> QNX: copy some std::error unit tests into a UI test

tests/ui/lint/rfc-2383-lint-reason/lint-attribute-only-with-reason.rs, tests/ui/self/elision/ignore-non-reference-lifetimes.rs, tests/ui/self/elision/multiple-ref-self-async.rs, tests/ui/self/elision/multiple-ref-self.rs, tests/ui/self/elision/no-shadow-pin-self.rs, tests/ui/self/elision/ref-assoc-async.rs, tests/ui/self/elision/ref-assoc.rs, tests/ui/self/elision/ref-self-async.rs, tests/ui/self/elision/ref-self-multi.rs, tests/ui/self/elision/ref-self.fixed, tests/ui/self/elision/ref-self.rs
To note: 
- New paragraphs: [7:2](https://spec.ferrocene.dev/values.html#fls_CUJyMj0Sj8NS), [7:3](https://spec.ferrocene.dev/values.html#fls_kaomYy0Ml4Nh), [7:4](https://spec.ferrocene.dev/values.html#fls_B5cmkWfD5GNt), [7:11](https://spec.ferrocene.dev/values.html#fls_oqhQ62mDLckN), [7:12](https://spec.ferrocene.dev/values.html#fls_uhwpuv6cx4ip), [7:13](https://spec.ferrocene.dev/values.html#fls_xuuFKmm181bs)
- These have no changes in here as they are either term definitions for the spec or undefined behavior descriptions
- The following pattern changes are already correctly annotated, this is due to their tests having been added to `tests\ui\half-open-range-patterns` which hosts a `tests\ui\half-open-range-patterns\ferrocene-annotations` file with the correct annotations:
- Changed …
=> Annotate tests for spec changes

.github/workflows/commit.yml
This is done because this check has been taking almost 10 minutes regularly and it is being cancelled from time to time
=> Increase the timeout for checks

ferrocene/doc/index/index.html, ferrocene/doc/user-manual/src/overview.rst
While #874 added the IEC 62304 bits in a bunch of places, we seem to have missed a couple spots.
I'm not sure if the wording is right since I understand Medical is more certification than qualification?
=> Mention IEC 62304 in more places

.circleci/workflows.yml
Yesterday @Dajamante  noticed our QNX jobs implicitly depend on the `ubuntu-24` container existing, but the `full` workflow may not actually build it (typically, `commit` does, but we recently moved `commit` to GHA).
This PR adds a `ubuntu-24` job to `full`.
=> Make QNX jobs depend on a new ubuntu-24 job in full

Cargo.toml, src/bootstrap/src/ferrocene/dist.rs
While trying to build ferrocene inside of a network-less sandbox, a user reported the following error while running `x.py test`:
```
tidy check
thread 'deps (.)' panicked at src/tools/tidy/src/deps.rs:575:24:
cmd.exec() failed with `cargo metadata` exited with an error:     Updating git repository `https://github.com/rust-lang/team`
warning: spurious network error (3 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
warning: spurious network error (2 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
warning: spurious network error (1 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
error: failed to get …
```
=> Exclude rustc-perf site from . workspace

library/Cargo.toml
A dependency (miniz_oxide) that once used adler now uses adler2
=> avoid build warning

.circleci/workflows.yml, ferrocene/ci/docker-images/ubuntu-20/Dockerfile, ferrocene/ci/docker-images/ubuntu-24/Dockerfile
In #1050 I missed the dockerfiles.
This means the dockerfiles no longer setup the venv/python pin, however since most uses mount the local directory in, if it's setup there, it'll still work.
=> Dockerfiles version lock uv as well

ferrocene/tools/traceability-matrix/src/annotations.rs, ferrocene/tools/traceability-matrix/templates/report.html, src/tools/compiletest/src/ferrocene_annotations.rs
To test:
```bash
./x.py run traceability-matrix
```
Review `build/x86_64-unknown-linux-gnu/doc/qualification/traceability-matrix.html` in your browser.
Search `um_rustc_C_codegen_units` and hit "Show linked tests", observe the `rmake.rs` note:
=> Repair rmake annotation detection

ferrocene/ci/formulae/gcc-arm-embedded.rb, ferrocene/ci/scripts/setup-darwin.sh
Works around the `gcc-arm-embedded` package being a 404 on Arm's mirrors.
Since `brew install --cask` won't work with old versions, we need to manually copy the old formulae in and use it.
=> Fix setup-darwin.sh pointing at a broken gcc-arm-embedded

ferrocene/ci/configure.sh, ferrocene/tools/generate-tarball/src/generator.rs
The `download-ci-llvm` config option is currently not working
```toml
[llvm]
download-ci-llvm = true
```
If a user tries to use it they'll get something like
```
download: s3://ferrocene-ci-artifacts/ferrocene/dist/fb8e927c45ed5d7861fb9ff4b9e55ece779a4382/rust-dev-aarch64-unknown-linux-gnu-fb8e927c4.tar.xz to build/tmp/rust-dev-aarch64-unknown-linux-gnu-fb8e927c4.tar.xz
extracting /home/ana.linux/git/ferrocene/ferrocene/build/cache/llvm-fb8e927c45ed5d7861fb9ff4b9e55ece779a4382-false/rust-dev-aarch64-unknown-linux-gnu-fb8e927c4.tar.xz to /home/ana.linux/git/ferrocene/ferrocene/build/aarch64-unknown-linux-gnu/ci-llvm
thread 'main' panicked at src/core/config/config.rs:1336:13:
fs::read_to_string(file) failed with No such file or directory (os error 2) ("config file …
```
=> Repair `download-ci-llvm` via including overlay in `rust-dev` component

ferrocene/doc/sphinx-shared-resources/exts/ferrocene_domain_cli/domain.py
Fixes the flake8 warning in sphinx-shared-resources (line was too long)
=> Fix flake8 warning in sphinx-shared-resources

.github/workflows/commit.yml
We missed this when moving to GHA and it's been impacting the beta pull upstream.
(Props to @pvdrz who dug into this with me majorly)
=> Unshallow on the beta channel

ferrocene/tools/backport/utils/update-last-message.py
Backport CI runner has Python 3.10, but this syntax was only introduced in Python 3.12. This resulted in backports failing.
=> use Python syntax known by Ubuntu 22.04

bors.toml
Had a sad case on an anticipated CI run succeed, but having it take 3h14m resulted in bors fail.
=> bump ci timeout to 4h

.github/workflows/automation-backport.yml
=> backport ci runner: no need to install python3-requests

.github/workflows/automation-pull-upstream.yml
This adds a check :ballot_box_with_check:  selector to the upstream pull action so we can choose which branches will be pulled (`master`, `beta`, `stable`). 
The default behavior still is that the three of them are pulled so the only added value here is to save CI time and remove clutter if you only want manually trigger an upstream pull from a particular branch.
=> Allow choosing which branches go in an upstream pull

ferrocene/ci/configure.sh
As detailed in https://public-docs.ferrocene.dev/main/qualification/internal-procedures/release/stable.html#uploading-the-qualification-technical-report, this sets the technical report URL for the upcoming, qualified, 24.11 release.
An example of this change in 24.08: https://github.com/ferrocene/ferrocene/blob/0b9a49099034657140d565f8129e4990881ff296/ferrocene/ci/configure.sh#L336-L343
Please review the linked document and ensure that this lists a file:
```
aws --profile ferrocene-ci s3 ls s3://ferrocene-ci-mirrors/manual/tuv-technical-reports/2024-11-22-ferrocene-24.11-technical-report.pdf
```
You should also download it and confirm the the file appears the same format of [24.05](https://docs.ferrocene.dev/stable-24.05/qualification/technical-report.pdf) and …
=> [1.81] add technical report

ferrocene/ci/channel
Follows the release process as detailed in https://public-docs.ferrocene.dev/main/qualification/internal-procedures/release/stable.html#publishing-a-stable-release.
No special review steps, just normal.
=> Move 24.11/1.81 to stable for release

.github/workflows/automation-pull-upstream.yml
Fixes a bug where scheduled runs of upstream pulls failed due to having an empty matrix.
cc @Dajamante
=> Trigger pulls for all branches on schedule

ferrocene/tools/pull-subtrees/pull.py
self.subtree includes a lot more than just a branch name
in addition, we don't even need a branch name (to be part of the automated pr branch name), for we never pull more than one branch at all for any of the subtrees
that is, this is enough: automation/pull-subtree-jkc4w0dm
we don't need it to be: automation/pull-subtree-main-jkc4w0dm
=> unbreak subtree pulls

ferrocene/ci/scripts/calculate-release-job-matrix.py
Also, it is advised to use sys.exit instead, which has same behavior.
=> exit was already assigned a bool

.circleci/workflows.yml
While looking at the CircleCI jobs and comparing them with some of the GHA I'm working on, I noticed that the grouping/ordering was kinda disjoint and we had our old commit-checks just lazing around.
=> Better group some circleCI tasks, remove dead commit-checks task

.github/workflows/commit.yml, ferrocene/ci/scripts/detect-unused-cargo-patches.py
This PR adds a script to run in CI to reject PRs containing unused Cargo patches. This is likely due to a subtree falling behind.
Note that this PR will most likely fail CI for now, as the libc subtree is behind.
=> Reject PRs with unused Cargo patches

ferrocene/tools/pull-upstream/automation.py, ferrocene/tools/pull-upstream/generate_pr_body.py, ferrocene/tools/pull-upstream/pull.sh
Right now the pull upstream automation displays some warnings in its output when it does something requiring manual action from the members of the PR rotation. This is far from ideal: if the person reviewing the PR wants to look at them, they'd have to find the GitHub Actions workflow that created the PR and sift through tons of log messages to find them.
This PR improves the situation by adding a new function to `pull.sh`: `automation_warning`. When the function is called, the warning will be displayed with emphasis in the logs and it will be recorded in a separate file. The automation will then include all of those warnings at the top of the description of the created PR, highlighting them for the reviewers.
Right now I only converted to this system the warnings that require explicit …
=> Show pull upstream warnings in the generated PRs

.github/workflows/merged-in-labels.yml, ferrocene/ci/scripts/add-merged-in-label.py
I recently labeled every PR in the repository with the new `merged-in:*` label, which indicates which Rust release was the PR merged in. This will be of great help when deciding what to backport. This PR adds a workflow that automatically applies the label to all merged PRs.
While the workflow is untested (of course), I tested the script locally.
=> Add workflow to automatically add the "merged-in:*" label

.github/workflows/merged-in-labels.yml
Forgot to add it, and it's causing the workflow to fail.
=> Pass the github token to the merge label automation

RELEASES.md, ferrocene/doc/safety-manual/src/customer-interactions.rst, ferrocene/doc/safety-manual/src/known-problems.rst
Backports
* #1244 
Also backports https://github.com/rust-lang/rust/pull/129960/commits/24906b593066da249b07a409af323f17a2840ca5 which which upstream is also doing: https://github.com/rust-lang/rust/pull/135934
In the case of 24906b593066da249b07a409af323f17a2840ca5, this is somewhat of a special circumstance. We noticed during our own release process that our 1.81 (so 24.11) release notes had changed and this change (along with https://github.com/rust-lang/rust/pull/126967 which was removed with https://github.com/rust-lang/rust/pull/129995) had disappeared. We confirmed the fix for https://github.com/rust-lang/rust/pull/129960/ is indeed in tree, but upstream never ported the release note update to their main branch. This port is being done in …
=> [1.83] Backport KP docs, release notes fix

.github/workflows/automation-pull-upstream.yml, ferrocene/ci/scripts/clone-empty-submodule.sh, ferrocene/tools/pull-upstream/pull.sh
This PR fixes the pull automation failing because `git diff-index --quiet HEAD` misreported the state of the index. While I was at it, I also shaved 8 minutes off the CI job by avoiding to clone GCC and Enzyme, using a script inspired by the existing `clone-llvm-subset.sh` script.
=> Fix pull automation not working

ferrocene/doc/release-notes/src/25.02.0.rst
Since the KP tool now lists KPs fixed per version, remove that from the release notes and link to it instead.
=> Update release notes to link to KP page

src/stage0
This will allow the build system to automatically retrieve the correct test outcomes without having to manually inject them on the 1.83 branch. I will also make a followup PR later to automatically do this for all of our branches.
=> [1.83] Fix downloading from CI on the `release/1.83` branch

Cargo.lock, ferrocene/tools/document-signatures/Cargo.toml, ferrocene/tools/document-signatures/src/main.rs, ferrocene/tools/document-signatures/src/sign.rs, ferrocene/tools/document-signatures/src/signature_files.rs, ferrocene/tools/document-signatures/src/verify.rs, src/bootstrap/src/core/builder/mod.rs, src/bootstrap/src/core/config/flags.rs, src/bootstrap/src/ferrocene/sign/mod.rs, src/etc/completions/x.fish, src/etc/completions/x.ps1, src/etc/completions/x.py.fish, src/etc/completions/x.py.ps1, src/etc/completions/x.py.sh, src/etc/completions/x.py.zsh, src/etc/completions/x.sh, src/etc/completions/x.zsh
This PR makes two changes to the `./x sign` command, learning from today's signing procedure:
* Signing a document will now do nothing if the document is already signed by all roles, and the signatures are up to date. This behavior can be overridden by passing `--force`.
* Running `./x sign` without any argument will attempt to sign all documents.
The result of these two changes is that Florian will now need to run only `./x sign`, both during the first signature of the release cycle, and during followup signatures of the same release. In the first case the command will sign all documents, and in the second it will only sign the changed documents.
=> Improve the document signing UX

.github/workflows/commit.yml
Forward port of the change in https://github.com/ferrocene/ferrocene/pull/1277.
=> Disable bootstrap's AWS access in commit checks

ferrocene/ci/split-tasks.py
`./library/core` unit tests have been moved into `./library/coretests`
`./library/core` still contains doc tests, however, so it should still be executed
=> ci: also run the `library/coretests` group

bors.toml
Was a typo in https://github.com/ferrocene/ferrocene/pull/1116.
=> Fix bors timeout (40h to 4h)

.github/workflows/commit.yml, ferrocene/ci/scripts/fix-stage0-branch.py, ferrocene/tools/pull-upstream/pull.sh
Downloads from CI work transparently on the main branch, both for LLVM and the test outcomes. They were historically broken on release branches though, due to bootstrap not being able to identify the correct parent commit.
The general fix for the issue is to update `nightly_branch` in `src/stage0` with the name of the base branch, which is `release/1.NN` for release branches. Since the branch name needs to be updated as soon as we branch off from `main`, this PR changes the upstream pull script to ensure the branch name is correct.
This also adds a CI check to ensure the branch name is correct, in case the automation fails to update it for whatever reason.
:warning: Merging this PR will break pulls from upstream beta and stable until the PR is backported to the relevant branches. The …
=> Fix download from CI in release branches by updating `src/stage0`

ferrocene/doc/internal-procedures/src/index.rst, ferrocene/doc/internal-procedures/src/setup-local-env.rst, ferrocene/doc/internal-procedures/src/testing-other-targets.rst
A first brush at a page describing how to replicate our bare-metal testing locally.
I'd like to circle back and add QNX later, as the steps are a bit different and require licensing notes. For now, the people with QNX licenses already know how to run the tests.
=> Add page documenting how to test other targets

ferrocene/doc/internal-procedures/src/docs/sphinx-extensions.rst, ferrocene/doc/internal-procedures/src/release/stable.rst, ferrocene/doc/release-notes/exts/ferrocene_relnotes/upcoming_release.py, ferrocene/doc/sphinx-shared-resources/src/ferrocene_qualification/__init__.py, ferrocene/doc/sphinx-shared-resources/src/ferrocene_qualification/upcoming.py, ferrocene/doc/sphinx-shared-resources/src/ferrocene_theme/static/ferrocene.css
This PR adds the `:upcoming:` Sphinx role, which allows to mark a part of the document as "coming soon". The role displays a yellow badge, and can be put either inside of a paragraph/list/table, or in the header of a page/section:
```rst
This is a paragraph describing a new feature :upcoming:`25.05`.
Exciting new feature :upcoming:`25.05`
======================================
```
The badge will be shown if the documentation is built outside of a release branch (so, on the `nightly`, `pre-rolling` and `rolling` channels), or if the version of the current release channel is lower than the version specified as the argument. In other cases the badge will not be rendered. There is no difference of public-docs vs customer docs.
When put in the page title, it will also show up in the table of …
=> Add the `:upcoming:` Sphinx role

ferrocene/tools/pull-upstream/automation.py
Discovered it in https://github.com/ferrocene/ferrocene/pull/1311. Turns out that `.strip("\n")` created a `[""]`, which is not coerced to false by Python's `if`.
=> Fix automation showing warning boilerplate when not needed

ferrocene/packages.toml
The builder for it was temporarily disabled in https://github.com/ferrocene/ferrocene/pull/1263 due to a build failure, but OxidOS was still referenced in the list of packages to release. When re-enabling OxidOS support please also revert this PR, in addition to https://github.com/ferrocene/ferrocene/commit/bbf674cdef2d30d574650048e8b22f2e3d5dd853.
=> Avoid distributing OxidOS

ferrocene/doc/sphinx-shared-resources/pyproject.toml, ferrocene/doc/sphinx-shared-resources/src/ferrocene_standalone_make_cli.py, ferrocene/doc/uv.lock
We need to remove `build/html` dir on clean build.
=> Remove build dir on --clear build

ferrocene/doc/internal-procedures/src/testing-other-targets.rst
I am a goose and totally forgot this env var. While it's not required to run the tests on the `aarch64-unknown-linux-gnu` host, we do have a test that checks for it now and that needs to be satisfied.
If you're merging this, please try to merge it alongside another PR since I'd be sad to gum up the CI with just this.
=> Add QEMU_CPU to steps for testing on aarch64 hosts

ferrocene/tools/traceability-matrix/templates/report.html, ferrocene/tools/traceability-matrix/templates/report.js, ferrocene/tools/traceability-matrix/templates/style.css
This PR adds buttons to expand and collapse all elements of the traceability matrix. Unfortunately clicking the buttons takes a couple of seconds to work, due to the large amount of `<details>` we have. I chose not to style the buttons since the OS provide good feedback about a button being "stuck" while it works, and recreating that was a bit overkill.
While I was at it I also tweaked the design of the page, to have the header bar and the section title be sticky at the top of the page.
[Screencast from 13-02-2025 14:52:07.webm](https://github.com/user-attachments/assets/44dafcc5-72bb-468b-bfa8-260b0a713fb7)
=> Add buttons to expand/collapse all elements of the traceability matrix

ferrocene/ci/scripts/require-uv-shebang.py
While making an unrelated change I discovered that we were checking for the `#!/usr/bin/env -S uv` shebang, not `#!/usr/bin/env -S uv run` shebang. Turns out that the script still passed because it was checking the first line *starts* with that shebang, not that it matches the shebang exactly. This PR fixes that.
=> Ensure we use the correct uv shebang

ferrocene/doc/user-manual/src/targets/index.rst
While reviewing our docs I noticed we didn't have our typical disclaimer here like we do on other qualified targets.
=> Add standard qualified disclaimer to thumbv7em

ferrocene/doc/qualification-plan/src/development.rst
We're moving away from FDs, instead, detail how we use our PM boards.
=> Move away from FD, detail how we use our PM system

ferrocene/ci/scripts/setup-windows.sh
I noticed in https://github.com/ferrocene/ferrocene/pull/1353#issuecomment-2694885274 that the zstd hash was failing in the latest choco package, this pins it back.
=> Fix the hash mismatch in zstd on Windows

.github/workflows/automation-pull-subtrees.yml
This will hopefully fix the spurious failure we've been seeing in the subtree pull job.
The error message referred to the tree being dirty, which shouldn't happen (it's a fresh checkout anyway). Also, only the first subtree fails, the others work correctly.
When I added debug logging in a job the problem stopped happening, probably because either the debugging code (a `git status`) updated some internal git data structures, or because it is a timing issue and the extra code made the job take slightly longer.
In my past experience a lot of these problems can happen with parallel subtree pulls, so this PR removes them.
=> Stop pulling submodules in parallel in `pull-subtrees`

ferrocene/ci/scripts/prepare-docs-to-github-pages.py, ferrocene/doc/breadcrumbs/ferrocene-breadcrumbs.css, ferrocene/doc/index/index-assets/index.css, ferrocene/doc/index/index.html, ferrocene/doc/public-docs-warning/README.md, ferrocene/doc/public-docs-warning/header.html, ferrocene/doc/public-docs-warning/public-docs-warning.css, ferrocene/doc/sphinx-shared-resources/src/ferrocene_theme/layout.html, ferrocene/doc/sphinx-shared-resources/src/ferrocene_theme/static/ferrocene.css, src/bootstrap/src/ferrocene/doc.rs, src/tools/linkchecker/main.rs
This PR adds a warning banner to https://public-docs.ferrocene.dev, to clarify the documentation comes from the main branch and might be inaccurate:
Feel free to review the code, but the messaging will need tweaking (we'll discuss this outside the PR). This PR is best reviewed commit-by-commit.
To get the banner on a local build (eg `./x.py doc ferrocene/doc/internal-procedures --open`, perform the step that `prepare-docs-to-github-pages.py` would do:
```bash
cp ferrocene/doc/public-docs-warning/public-docs-warning.css build/host/doc/public-docs-warning.css
```
=> Show a warning banner on public-docs

.circleci/workflows.yml, .github/workflows/commit.yml, config.example.toml, ferrocene/ci/configure.sh, src/bootstrap/defaults/config.ferrocene-dist.toml, src/bootstrap/src/core/build_steps/setup.rs, src/bootstrap/src/core/config/config.rs
Note: currently a draft as I needed to cherry-pick rust-lang/rust#137220 (it hasn't reached Ferrocene yet).
This PR moves most of the configuration for our CI away from `configure.sh` and into a bootstrap profile. With this change, all of the configuration about how a Ferrocene build should look like will reside in the profile, and `configure.sh` will only contain settings specific to our CI environment.
I also made a few changes:
* Added `ferrocene.channel = "auto-detect"` to load the channel from `ferrocene/ci/channel`. Before we were loading the contents of the file in the bash script, but that's not possible anymore. This mirrors the change we upstreamed in rust-lang/rust#137220.
* Added `FERROCENE_TEST_OUTCOMES_DIR` to load the test outcomes from a directory. Before this was done …
=> Move most of `configure.sh` to a bootstrap profile

tests/run-make/ferrocene/compiler-arguments/out-dir/rmake.rs, tests/run-make/ferrocene/compiler-arguments/upper_c_debuginfo/upper_c_debuginfo_multiple/rmake.rs, tests/run-make/ferrocene/compiler-arguments/upper_c_extra-filename/upper_c_extra-filename/rmake.rs, tests/run-make/ferrocene/compiler-arguments/upper_c_extra-filename/upper_c_extra-filename_mir/rmake.rs, tests/run-make/ferrocene/compiler-arguments/upper_c_extra-filename/upper_c_extra-filename_repeat/rmake.rs, tests/run-make/ferrocene/compiler-arguments/upper_c_link-arg/upper_c_link-arg/rmake.rs, tests/run-make/ferrocene/compiler-arguments/upper_c_link-arg/upper_c_link-arg_multiple/rmake.rs, tests/run-make/ferrocene/compiler-arguments/upper_c_no-vectorize-loops/rmake.rs
This should imply that the tests only run on the specified edition.
=> remove misleading edition args

ferrocene/ci/split-tasks.py
This was needed at the time, but has since been changed, such that './x test library/core' also tests library/coretests.
This reverts commit fd246937731fce6a7cc26aecf8ba78631084de03.
=> no need to specify library/coretests separately

src/bootstrap/src/ferrocene/dist.rs
Upstream recently added an automated way of generating copyright files (https://github.com/rust-lang/rust/pull/135588), so we also need to do similar, because we have a different way of generating release tarballs.
=> add complete copyright/licensing info to source tarball

ferrocene/doc/internal-procedures/src/testing-other-targets.rst
We previously changed to using `x test library/coretests` instead of `x test library/core` because unit tests were moved to a separate crate, "library/coretest". But later, a change was made so that `x test library/core` also tested unit tests in that crate.
One advantage of switching back to `x test library/core` is that doc tests are also executed.
(this should have been part of 8ae5c72a38d84d6e276ebe24196300637120bfe4)
=> "x test library/core" now also tests "library/coretests"

src/bootstrap/Cargo.toml, src/bootstrap/src/ferrocene/dist.rs
This reverts commit 210ca50f4b5f12f6f417e6e29f63aef50be7ef07 and adds a permanent fix to the panic when distributing `ferrocene-src`.
This panic happened because the 2024 edition uses the 3 resolver which is version aware and requires the `rustc` binary to fetch the compiler version.
To fix it, we replicate 61339997194448cd8b18b422f32ced0126963213 in ferrocene's `dist` script.
=> Fix `./x dist ferrocene-src`

ferrocene/tools/traceability-matrix/src/annotations.rs, ferrocene/tools/traceability-matrix/templates/report.html
The traceability matrix supports annotations being defined in a makefile (for run-make tests). Now that those tests have been removed, we should remove support for Makefiles in our tooling.
=> remove support for Makefiles

ferrocene/doc/internal-procedures/src/release/stable.rst
The text implies that each major releases is *always* accompanied by point releases, which is not true. We have in fact not had a single point release so far.
=> point releases are not guaranteed to happen

ferrocene/doc/internal-procedures/src/release/stable.rst
A few grammar fixes to the "Branching from rolling into beta" section of the release procedures
=> more text fixes to the release procedure

README.md, TRADEMARK.md
All open source Ferrocene work assigns copyright to "The Ferrocene Developers", but we had some files that assigns it to "Ferrous Systems GmbH".
This is also not accurate in that Ferrocene contributions are at times external to Ferrous Systems.
[internal ticket](https://app.clickup.com/t/86949v552)
=> replace wrong/inconsistent copyright assignment

src/bootstrap/src/core/build_steps/test.rs
In CI we pass the `--ferrocene-test-one-crate-per-cargo-call` flag to ensure each crate shows up as a separate line in our qualification report, but a recent upstream change broke it:
Since core's test suite is split between core and coretests (and the alloc test suite is split between alloc and alloctests), upstream recently changed bootstrap to run both core and coretests when testing `library/core`. This is done *after* our implementation of `--ferrocene-test-one-crate-per-cargo-call`, which would result in coretests and alloctests being executed twice.
This PR fixes the problem by suppressing the implicit addition of coretests and alloctests when the flag is passed. They will still be tested standalone.
=> Don't add coretests to core when testing crates individually

ferrocene/doc/evaluation-report/src/rustc/method.rst, ferrocene/doc/sphinx-shared-resources/src/ferrocene_domain_cli/domain.py, ferrocene/doc/sphinx-shared-resources/src/ferrocene_theme/static/ferrocene.css, ferrocene/doc/user-manual/src/rustc/cli.rst, ferrocene/doc/user-manual/src/rustfmt/cli.rst, tests/ui/ferrocene/compiler-arguments/codegen/codegen_C.rs, tests/ui/ferrocene/compiler-arguments/codegen/codegen_C.stderr, tests/ui/ferrocene/compiler-arguments/codegen/codegen_bad-syntax.rs, tests/ui/ferrocene/compiler-arguments/codegen/codegen_bad-syntax.stderr, tests/ui/ferrocene/compiler-arguments/codegen/codegen_codegen.rs, tests/ui/ferrocene/compiler-arguments/codegen/codegen_codegen.stderr, tests/ui/ferrocene/compiler-arguments/codegen/codegen_no-option.rs, tests/ui/ferrocene/compiler-arguments/codegen/codegen_no-option.stderr, tests/ui/ferrocene/compiler-arguments/upper_c/upper-c.rs, tests/ui/ferrocene/compiler-arguments/upper_c/upper-c_codegen.rs, tests/ui/ferrocene/compiler-arguments/upper_c/upper-c_codegen.stderr, tests/ui/ferrocene/compiler-arguments/upper_c/upper-c_eq.rs, tests/ui/ferrocene/compiler-arguments/upper_c/upper-c_eq.stderr, tests/ui/ferrocene/compiler-arguments/upper_c/upper-c_hyphen-hyphen.rs, tests/ui/ferrocene/compiler-arguments/upper_c/upper-c_no-option.rs, tests/ui/ferrocene/compiler-arguments/upper_c/upper-c_no-option.stderr, tests/ui/ferrocene/compiler-arguments/upper_c/upper-c_no-space.rs, tests/ui/ferrocene/compiler-arguments/upper_c/upper-c_unknown-option.rs, tests/ui/ferrocene/compiler-arguments/upper_c/upper-c_unknown-option.stderr, tests/ui/ferrocene/compiler-arguments/upper_c/upper-c_upper-c.rs, tests/ui/ferrocene/compiler-arguments/upper_c/upper-c_upper-c.stderr
When considering how to test CLI flags, we categorized them internally in informational, narrow impact, or high impact. We used this terminology when talking to assessors too, but we never actually wrote it down in the qualification material. This PR adds our categorization criteria to the evaluation report, and actually categorizes each CLI flag in the user manual.
Categories can be set by adding the required `:category:` option to the CLI argument directive, as it is currently done in `cli.rst`. The extension will verify the value belongs in an allowlist, and it will automatically style the list.
Along with the changes I spent a bit of time improving the styling of the CLI page:
| Before | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/fa362647-641e-4a5f-8d3b …
=> Add testing categories to the CLI docs

ferrocene/doc/index/index.html, src/bootstrap/src/core/builder/mod.rs, src/bootstrap/src/ferrocene/dist.rs, src/bootstrap/src/ferrocene/doc/mod.rs
this pr has 2 main purposes
- adds copyright files to the doc tarball
- references the copyright files from Ferrocene docs index
context:
- at the moment, we only include copyright files in the ferrocene source tarball
- this pr is a convenience that lets users view the copyright files without having to first download and extract the source tarball
[internal ticket](https://app.clickup.com/t/8697wq828)
=> include copyright files in docs

.circleci/workflows.yml, ferrocene/doc/internal-procedures/src/index.rst, ferrocene/doc/internal-procedures/src/test-variants.rst, ferrocene/doc/qualification-plan/src/ci.rst, ferrocene/doc/qualification-report/exts/ferrocene_test_outcomes/outcomes.py, ferrocene/doc/qualification-report/src/templates/tests.jinja2, ferrocene/tools/traceability-matrix/src/annotations.rs, ferrocene/tools/traceability-matrix/src/matrix.rs, ferrocene/tools/traceability-matrix/src/report.rs, ferrocene/tools/traceability-matrix/src/test_outcomes.rs, src/bootstrap/src/core/build_steps/test.rs, src/bootstrap/src/core/builder/tests.rs, src/bootstrap/src/core/config/flags.rs, src/bootstrap/src/ferrocene/mod.rs, src/bootstrap/src/ferrocene/test_variants.rs, src/build_helper/src/metrics.rs, src/etc/completions/x.fish, src/etc/completions/x.ps1, src/etc/completions/x.py.fish, src/etc/completions/x.py.ps1, src/etc/completions/x.py.sh, src/etc/completions/x.py.zsh, src/etc/completions/x.sh, src/etc/completions/x.zsh
Test variants are a mechanism to run a test suite multiple times for each target, each time with a different configuration. For example, it can be used to test multiple editions, or multiple QEMU emulated CPUs.
The high level overview is that variants are defined in `src/bootstrap/src/ferrocene/test_variants.rs`, and they can be enabled by passing the `--test-variant=NAME` flag to `./x test`:
```
./x test tests/ui --test-variant=2021
```
> [!NOTE]
>
> Currently the 2021 test variant actually runs tests for the 2015 edition. This should be changed once we update the test suite.
Test variants are then propagated to the qualification report (each variant will be a separate line in the report), and in the traceability matrix (the matrix needs to cover all `(target, variant)` tuples). CI is …
=> Implement test variants

ferrocene/doc/qualification-report/src/templates/tests.jinja2
After https://github.com/ferrocene/ferrocene/pull/1421 got merged, I noticed that the template wouldn't include anything when no test variable was available:
This PR quickly fixes it by adding a dash:
=> Show a dash when there is no test variant

src/bootstrap/src/core/builder/cargo.rs
For Ferrocene we configure both the compiler and the standard library to be compiled with debug assertions, to be able to potentially catch more issues in our qualified products. Bootstrap doesn't have a separate setting for controlling the debug assertions of tools, and they thus inherit the setting from rustc.
A customer though reported hitting [this debug assertion in Cargo](https://github.com/rust-lang/cargo/blob/2887f0755466903c3437077a227227b2f65f4e1c/src/cargo/core/resolver/types.rs#L69-L77). The assertion is meant to only be used when executing the test suite, which hints to me that the Cargo team assumes builds with debug assertions are never shipped to end users. This PR quickly patches the problem by disabling debug assertions for tools.
This is a quick patch to get the fix to …
=> Build tools without debuginfo

bootstrap.example.toml, ferrocene/doc/internal-procedures/src/code-coverage.rst, ferrocene/doc/internal-procedures/src/index.rst, ferrocene/doc/internal-procedures/src/setup-local-env.rst, src/bootstrap/src/core/build_steps/test.rs, src/bootstrap/src/core/config/config.rs, src/bootstrap/src/ferrocene/code_coverage.rs, src/bootstrap/src/ferrocene/mod.rs, src/bootstrap/src/ferrocene/test_outcomes.rs
:warning: This PR builds on top of https://github.com/ferrocene/ferrocene/pull/1421, commits from it are present here :warning: 
This PR adds the last piece of the puzzle for coverage, `coverage-outcomes = "download-ci";`, to download the latest coverage metadata from CI when generating a report locally. It also adds documentation for the whole coverage work.
=> Document coverage and add download-ci for it

ferrocene/tools/pull-subtrees/subtrees.yml
The FLS now lives at https://github.com/rust-lang/fls. This PR updates the repo we pull in with our subtree pull automation.
=> Update the spec repo we pull from

ferrocene/doc/qualification-plan/src/organization.rst
I'll leave Ferrous on May 8th, so this PR removes me from the organization roles. On the side I'm updating the permissions to grant Ana the release management permissions.
=> Remove myself from organization roles (as I'm leaving Ferrous)

src/bootstrap/defaults/bootstrap.ferrocene-dist.toml
Turns out we weren't doing this, and we should!
You can test this by doing `uv run x.py dist rustc` and expanding the `build/rustc-*.tar.xz` to see in `libexec` there is the `rust-analyzer-proc-macro-srv` binary.
Re: https://github.com/ferrocene/ferrocene/blob/466de87e29b9086f5cc5b2a4cd08bc4de1bcf4a1/src/bootstrap/defaults/bootstrap.ferrocene-dist.toml#L35
I do not *believe* we need to include this in `packages.toml`, since it's a component of `rustc`, not it's own package...
=> Distribute `rust-analyzer-proc-macro-srv` in `rustc` package

README.md
Noticed we were missing the new medical qualification in our README, so I updated it.
=> Update readme with new qualification

ferrocene/doc/internal-procedures/src/working-with-the-ci.rst
`miscelaneous` -> `miscellaneous`, whoops!
=> Fix spelling

src/bootstrap/src/ferrocene/test_outcomes.rs
This reverts commit fccdce16804f9392aa049d3719256acfae8ce6d5.
This cherry picked commit was not needed after the changes in c3f8514
=> Fix CI download of test outcomes

ferrocene/doc/internal-procedures/src/docs/signatures.rst, ferrocene/tools/document-signatures/diff.py
There is no guarantee that signatures will always validate, since they rely on the documentation process being fully deterministic. When signatures are not valid in CI, the debugging step requires comparing the documentation generated locally on the signing machine with the documentation generated in CI.
This PR adds (and document!) a script automating this process, generating a diff file that can be then sent to the engineers.
=> Add tool to generate a diff of the signed documentation

ferrocene/ci/split-tasks.py, ferrocene/tools/self-test/src/binaries.rs
... so we can build `rust-analyzer-proc-macro-srv`
Follow up on #1441 . I didn't notice it wasn't working since I didn't use `split-tasks.py` during testing.
When reviewing this PR, please make sure the CI uploaded rustc package has `libexec/rust-analyzer-proc-macro-srv` and that the `rust-analyzer` package is also uploaded using `aws s3 ls` and `aws s3 cp` on the urls in the "Upload Artifacts to S3" stage of the dist jobs.
=> Include rust-analyzer tool when building rustc 

src/bootstrap/src/core/build_steps/run.rs, src/tools/generate-copyright/src/cargo_metadata.rs, src/tools/generate-copyright/src/main.rs
We noticed that in our releases the out-of-tree notices were not being included. When `x.py run generate-copyright` was ran on local development machines, it worked fine.
After some investigations @tshepang and I determined that the problem was that the cargo registry (located in `CARGO_HOME`) started with the source directory on CI jobs, and was being excluded by this line:
https://github.com/ferrocene/ferrocene/blob/96a45dd9a18c6e54d3cd81750a78fe459fa48af0/src/tools/generate-copyright/src/cargo_metadata.rs#L85-L88
In our `run.sh` we set `CARGO_HOME` to be `build/cargo-home`:
https://github.com/ferrocene/ferrocene/blob/96a45dd9a18c6e54d3cd81750a78fe459fa48af0/ferrocene/ci/run.sh#L34-L46
This PR passes the `CARGO_HOME` variable to the `generate-copyright` tool and expands the …
=> Exclude `CARGO_HOME` from `generate-copyright` in-tree determination

ferrocene/doc/document-list/signature/signature.toml, ferrocene/doc/evaluation-plan/signature/signature.toml, ferrocene/doc/evaluation-report/signature/signature.toml, ferrocene/doc/internal-procedures/signature/signature.toml, ferrocene/doc/qualification-plan/signature/signature.toml, ferrocene/doc/qualification-report/signature/signature.toml, ferrocene/doc/safety-manual/signature/signature.toml
Documentation semantic diff:
* **Index**
* Added "Licensing and Copyright" pages
* **Document list**
* Version number changed
* Document IDs changed
* **Evaluation Plan**
* No semantically meaningful differences
* **Evaluation Report**
* Added "Compiler arguments affecting the compilation outcome"
* **Internal procedures**
* Updated "Handling Backports" * Clarified *feature* development happens on `main`
* Updated "Sphinx Extensions"
* Added "Marking changes as upcoming"
* Removed "Sphinx Needs Integration"
* Updated "Digital Signatures" * Removed "Signing documents" * Added "Signing all documents" * Added "Signing a single document" * Added "Configuring the roles allowed to sign" * Added "Inspecting the signature contents"
* Updated "Setting up a local development environment"
* Updated …
=> Sign Ferrocene 25.05

src/bootstrap/defaults/bootstrap.ferrocene-dist.toml
- `change-id` is informative, and needs only be set during development... it is not useful in CI
- `rust.description` is deprecated, and instead moved to build.description
=> ci: avoid some build warnings

Cargo.lock, src/tools/compiletest/Cargo.toml
The feature using this dep was removed before Ferrocne was open to the public
=> compiletest: remove unused dep

.github/workflows/commit.yml
Upstream now builds `rustc` before it can check `std`, because `std` can only be built with in-tree `rustc`. This is a lot for what is supposed to be a quick check.
=> ci: reduce runtime of Commit workflow

ferrocene/ci/split-tasks.py, ferrocene/doc/internal-procedures/src/docs/sphinx-extensions.rst, ferrocene/doc/internal-procedures/src/setup-local-env.rst, ferrocene/doc/internal-procedures/src/testing-other-targets.rst, ferrocene/doc/internal-procedures/src/working-with-the-ci.rst, ferrocene/doc/qualification-report/src/templates/tests.jinja2, ferrocene/doc/release-notes/src/24.05.0.rst, ferrocene/doc/release-notes/src/24.08.0.rst, ferrocene/doc/release-notes/src/24.11.0.rst, ferrocene/doc/release-notes/src/25.02.0.rst, ferrocene/doc/release-notes/src/25.05.0.rst, ferrocene/doc/release-notes/src/next.rst, ferrocene/doc/sphinx-shared-resources/src/ferrocene_qualification/target.py, ferrocene/doc/target-names.toml, ferrocene/doc/user-manual/src/rustc/cli.rst, ferrocene/doc/user-manual/src/targets/index.rst, ferrocene/tools/self-test/src/binaries.rs, ferrocene/tools/self-test/src/compile.rs, ferrocene/tools/self-test/src/env.rs, ferrocene/tools/self-test/src/linkers.rs, ferrocene/tools/self-test/src/targets.rs
Renames "target triples" to "target tuples" wherever I can find it.
=> Rename triple to tuple

ferrocene/ci/channel, ferrocene/ci/configure.sh
These steps:
* https://public-docs.ferrocene.dev/main/qualification/internal-procedures/release/stable.html#uploading-the-qualification-technical-report
* https://public-docs.ferrocene.dev/main/qualification/internal-procedures/release/stable.html#publishing-a-stable-release
=> [1.86] Upload technical report and make 1.86 stable

ferrocene/doc/qualification-report/src/rustc/thumbv7em-none-eabi.rst, ferrocene/doc/qualification-report/src/rustc/thumbv7em-none-eabihf.rst, ferrocene/doc/user-manual/src/targets/thumbv7em-none-eabi.rst, ferrocene/doc/user-manual/src/targets/thumbv7em-none-eabihf.rst
Remove the upcoming tags for 25.05 since we're now marking it stable (#1539 )
=> Remove upcoming 25.05 tags

library/core/src/intrinsics/mod.rs, library/core/src/lib.rs
- **Expose `sync` and `cell`**
- **Generate documentation even if intra-doc links are broken**
=> Generate docs for certified subset

ferrocene/doc/release-notes/src/25.05.0.rst
We've released it now! :)
Follows https://public-docs.ferrocene.dev/main/qualification/internal-procedures/release/stable.html#remove-upcoming-notes-in-the-main-branch
=> Remove upcoming from 25.05 release

library/core/src/alloc/layout.rs, library/core/src/clone.rs, library/core/src/cmp.rs, library/core/src/convert/mod.rs, library/core/src/hint.rs, library/core/src/intrinsics/mod.rs, library/core/src/macros/mod.rs, library/core/src/marker.rs, library/core/src/mem/mod.rs, library/core/src/num/int_macros.rs, library/core/src/num/uint_macros.rs, library/core/src/ops/control_flow.rs, library/core/src/ops/deref.rs, library/core/src/ops/drop.rs, library/core/src/ops/mod.rs, library/core/src/ops/range.rs, library/core/src/ops/try_trait.rs, library/core/src/option.rs, library/core/src/panic/location.rs, library/core/src/primitive_docs.rs, library/core/src/ptr/const_ptr.rs, library/core/src/ptr/metadata.rs, library/core/src/ptr/mod.rs, library/core/src/result.rs, library/core/src/ub_checks.rs
Thanks to the `allow(rustdoc::broken_intra_doc_links)` which was added in https://github.com/ferrocene/ferrocene/pull/1541, we can just add back all doc-comments as rustdoc will not complain about broken links anymore.
Generating docs for full libcore and for the subset work (tested locally) and include the whole doc-comment:
```console
$ ./x doc library/core
$ ./x doc library/core --set rust.std-features="['ferrocene_certified']"
```
=> libcore-cert: Add doc comments back

ferrocene/doc/user-manual/src/rustc/mixed-language.rst
On my system (Ubuntu 25.04) the static linking example gives
```console
$ gcc -o call_factorial_from_c -L . -l factorial call_factorial_from_c.c
/usr/bin/ld: /tmp/ccWY29f0.o: in function `main':
call_factorial_from_c.c:(.text+0xe): undefined reference to `factorial'
collect2: error: ld returned 1 exit status
```
Reordering arguments fixes the issue.
=> Fix linker arguments in mixed language example in user manual

ferrocene/packages.toml, src/bootstrap/defaults/bootstrap.ferrocene-dist.toml
We've bumped into some KPs that can be detected by `miri`. So, let's distribute it so that folks can use it without needing to reach for upstream.
=> Distribute `miri`

src/bootstrap/src/ferrocene/code_coverage.rs
Currently, we only use the `libstd` dynamic library as the instrumented
binary for coverage. However, we should use the binaries that were
executed to generate the coverage information instead. These changes
pass every single executable inside the `deps` directory to `llvm-cov`.
cc @hoverbear @urhengulas
=> Use all binaries for coverage

src/bootstrap/src/ferrocene/doc/mod.rs, src/bootstrap/src/ferrocene/run.rs, src/tools/compiletest/src/ferrocene_annotations.rs
This PR fixes a very annoying bug where a bunch of new empty folders were created in the root of the repository when getting the traceability matrix:
- **Rename `FERROCENE_SRC_BASE` to `FERROCENE_SRC_TEST_SUITE_ROOT`**
- **Set `Config::src_root` as well.**
- **Set `Config::build_root` and `Config::build_test_suite_root`**
cc: @hoverbear @tshepang
=> Set build folders for Ferrocene annotations

ferrocene/doc/internal-procedures/src/testing-other-targets.rst
Don't suggest shortcutting on Windows... I'm not sure how that slipped in there, it'd only be valid on `aarch64-*` Windows.
=> aarch64 testing is not shortcutted on x86_64 windows

ferrocene/doc/release-notes/src/next.rst
https://github.com/ferrocene/ferrocene/pull/1574 https://github.com/ferrocene/ferrocene/pull/1575 & https://github.com/ferrocene/ferrocene/pull/1566 enabled `miri`. This adds it to the release notes now that we've validated it works.
For now, we just defer to the upstream docs.
=> Add miri to release notes

library/coretests/tests/lib.rs, library/coretests/tests/ops.rs
This brings line coverage for `core::ops` to 100%:
- **Cover `RangeBounds::contains`**
- **Cover `RangeBounds` and `OneSidedRange`**
- **Cover `Debug` implementations of ranges**
=> Improve `core::ops` coverage

src/bootstrap/src/ferrocene/dist.rs
Following the ideas in #1513, we now add `trpl` as a customer who wants an offline vendor tarball now depends on it.
=> Add `trpl` vendor to ferrocene-src

ferrocene/ci/scripts/fix-stage0-branch.py
Fixes this warning from `./ferrocene/ci/scripts/fix-stage0-branch.py`:
```
/home/ana/git/ferrocene/ferrocene/ferrocene/ci/scripts/fix-stage0-branch.py:80: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/ana/git/ferrocene/ferrocene/src/stage0' mode='w' encoding='UTF-8'>
```
=> Fix `ferrocene/ci/scripts/fix-stage0-branch.py` not closing file

library/coretests/tests/alloc.rs
This brings line coverage for `core::alloc` to 100%
=> Improve `core::alloc` coverage

ferrocene/doc/qualification-plan/src/development.rst
Largely follow the recent Rust project discussions, as well as our own internal team experiences, in taking a stance where we reject so-called "Low effort" changes such as those which might be "Vibe coded."
=> Note that low effort contributions are rejected

.circleci/workflows.yml, library/core/Cargo.toml, library/std/Cargo.toml, library/sysroot/Cargo.toml
> [!NOTE]
> This is the first PR, of four expected ones, to merge the changes from libcore-cert into main.
Add the "ferrocene_certified" feature to libcore and add the most minimal CI which just ensures the certified subset builds and can produce docs.
You can test it locally by executing the same commands the CI is executing:
```console
$ ./x build library/core --set rust.std-features='["ferrocene_certified"]'
$ ./x doc   library/core --set rust.std-features='["ferrocene_certified"]'
```
The next PR will add the subset annotations.
=> Add "ferrocene_certified" feature to libcore and add minimal CI

library/coretests/tests/char.rs, library/coretests/tests/lib.rs
This brings line coverage for `core::ascii` to 99.5%
- **Cover `core::char::convert`**
- **Cover `core::char::methods`**
=> Improve `core::char` coverage

library/coretests/tests/fmt/builders.rs, library/coretests/tests/fmt/mod.rs, library/coretests/tests/fmt/num.rs, library/coretests/tests/lib.rs
This brings line coverage for `core::fmt` to 100%
- **Cover `core::fmt::builder`**
- **Cover `core::fmt::rt`**
- **Cover `core::fmt`**
=> Improve `core::fmt` coverage

tests/ui/asm/label-operand.rs
Backports https://github.com/rust-lang/rust/pull/143227 as we need it for satisfying traceability matrix.
=> [1.88] add test: inline assembly label operand

library/coretests/tests/intrinsics.rs
This brings line coverage for `core::intrinsic` to 87.41%
=> Improve `core::intrinsic` coverage

REUSE.toml, license-metadata.json, src/bootstrap/src/ferrocene/code_coverage.rs, src/bootstrap/src/ferrocene/dist/flip_link.rs, src/bootstrap/src/ferrocene/install.rs, src/bootstrap/src/ferrocene/secret_sauce.rs, src/bootstrap/src/ferrocene/sign/signature_files.rs, src/bootstrap/src/ferrocene/test_variants.rs, src/bootstrap/src/ferrocene/tool.rs, src/bootstrap/src/ferrocene/tool/flip_link.rs
Problem: All files in `src/**` have their copyright attributed to the Rust project. Files in `src/bootstrap/src/ferrocene` should (also) have their copyright attributed to Ferrocene. Usually this is done by adding the license header. But unfortunately this was forgotten a few times and `reuse` does not detect this problem, since it only detects if a file has no copyright at all. 
Solution: Therefore we modify REUSE.toml to attribute all files in `src/bootstrap/src/ferrocene` to Ferrocene as well. We still aim to add the copyright header. But in case we forget, the copyright is still there.
=> Fix `src/bootstrap/src/ferrocene` license

library/core/src/iter/traits/collect.rs
This fixes a small bug where we get the `collect` module for the certified subset coverage report even though it is gated.
=> Mark `collect` macro internals as uncertified

ferrocene/ignored-tests.toml, src/bootstrap/src/core/build_steps/compile.rs
Cherry pick a fix that was causing us not to use `lld` as the default on x86_64 Linux (*not* any of our qualified bare metal targets).
This should also get backported to other releases.
=> [1.88] Use LLD by default on x64 regardless of channel

.circleci/workflows.yml, compiler/rustc_driver_impl/src/lib.rs
This repairs code coverage inaccuracies on branches where `channel` is not set to `nightly`.
It's not determined why this is the case yet, but it fixes it for us locally.
Thanks @japaric for finding the line and confirming the fix.
If this works (we need to validate the artifacts) we will forward port this to main.
=> [1.88] Fixup code coverage

ferrocene/ci/split-tasks.py
We recently landed miri (#1566), however it would be better served in the `tools` tasks.
=> Miri should be in the tools tasks

ferrocene/tools/pull-upstream/generate_pr_body.py
Okay this is a funny/weird one.
In the commit message of https://github.com/rust-lang/rust/commit/41d8d85549fc90967912a32b5604801bf25d8ea7 there is a `^M`, but if you look at https://github.com/rust-lang/rust/pull/145644/ that commmit looks totally fine and non-suspect.
The funny part is Python enjoys interpreting this as a newline.
```python
>>> import subprocess
>>> out = subprocess.run(["git", "log", "--format='%H|%P|%s'", "--reverse", "-n", "1", "41d8d85549fc90967912a32b5604801bf25d8ea7"], text=True, stdout=subprocess.PIPE).stdout.strip()
>>> out.split("\n")
["'41d8d85549fc90967912a32b5604801bf25d8ea7|1ddb4d0062fbe55b88e55cffc00fe8b898512536|Remove ", "hs_abs_cmp examples'"]
>>> out.splitlines()
["'41d8d85549fc90967912a32b5604801bf25d8ea7|1ddb4d0062fbe55b88e55cffc00fe8b898512536|Remove …
```
=> Upstream pull automation can handle `^M` in commits

library/core/src/primitive_docs.rs
Some primitive types, like slice or pointer, have been omitted from the documentation. They were part of the subset, but just did not show up in the docs. This was not intended and is fixed by this PR. 
Before on the left, after on the right:
=> Show all primitive types in core library API docs

ferrocene/doc/core-certification/src/_static/api-docs/core/index.html, ferrocene/doc/core-certification/src/conf.py, ferrocene/doc/core-certification/src/subset-api-docs.rst, src/bootstrap/src/core/build_steps/doc.rs, src/bootstrap/src/core/builder/mod.rs, src/bootstrap/src/core/builder/tests.rs, src/bootstrap/src/core/config/target_selection.rs, src/bootstrap/src/ferrocene/dist.rs, src/bootstrap/src/ferrocene/doc/certified_api_docs.rs, src/bootstrap/src/ferrocene/doc/mod.rs, src/bootstrap/src/ferrocene/mod.rs, src/bootstrap/src/utils/cc_detect.rs, src/tools/linkchecker/main.rs
This PR automates building the API docs for the certified libraries, that is only the core library at the moment. This removes the need for the static HTML copy of the certified core API docs.
It introduces a new bootstrap command: `./x doc ferrocene-certified-api-docs`.
Also it makes the existing commands `./x doc ferrocene/doc` and `./x dist ferrocene-docs` also create the certified API docs.
=> Distribute the certified core library API docs

.circleci/workflows.yml
https://github.com/ferrocene/ferrocene/pull/1639 accidentally removed the job dependencies related to x86_64-linux-certified. This results in the job not being executed. This PR fixes that.
=> CI: Make sure the x86_64-linux-certified job is being run

ferrocene/ci/split-tasks.py
These tests are very slow and we frequently see them failing in pulls and CI for inscrutable reasons. Since `rustdoc` is not qualified, it's OK to not run these.
=> Disable rustdoc-js-std tests in compiletest job

ferrocene/doc/release-notes/src/25.08.0.rst
Follows through on https://public-docs.ferrocene.dev/main/qualification/internal-procedures/release/stable.html#publishing-a-stable-release and https://public-docs.ferrocene.dev/main/qualification/internal-procedures/release/stable.html#remove-upcoming-notes-in-the-main-branch
Pulls in https://github.com/ferrocene/ferrocene/pull/1768 https://github.com/ferrocene/ferrocene/pull/1774
=> 25.08 is released

.circleci/workflows.yml, .github/workflows/commit.yml
Recently the default `reuse` rose to 6.0.0 and we noticed we weren't pinned.
=> Pin reuse to 5.1.1

src/bootstrap/src/core/builder/tests.rs, src/bootstrap/src/core/config/target_selection.rs
Previously, all the tests would be skipped outside x64. This made it hard to debug and fix them, since they would only fail in CI. Make them platform-independent instead.
cc https://github.com/ferrocene/ferrocene/pull/1784, @tshepang
=> bootstrap self-test: make it possible to run tests for certified targets on macOS

.circleci/workflows.yml
Bootstrap doesn't generate metrics.json when it fails. Don't try uselessly to copy it.
See https://app.circleci.com/pipelines/github/ferrocene/ferrocene/13965/workflows/58a0c496-4178-4351-a27e-7a94028276ba/jobs/95493/parallel-runs/0/steps/0-110 for an example failure this would have avoided.
=> Don't generate a metrics report if the build fails
