ferrocene/doc/qualification-report/src/tests.rst
Reported [on Reddit](https://www.reddit.com/r/rust/comments/16zroj5/comment/k3jyvf0/?utm_source=reddit&utm_medium=web2x&context=3) by [u/hgomersall](https://www.reddit.com/user/hgomersall/). Thanks!
=> Fix typo in page title

ferrocene/tools/pull-upstream/pull.sh
Should hopefully fix https://github.com/ferrocene/ferrocene/issues/65.
=> Ensure submodules are initialized during upstream pulls

src/bootstrap/Cargo.lock
Trying to get around the failure seen in #86
=> bump serde and serde_derive

ferrocene/tools/pull-upstream/pull.sh
One of the goals of the pull-upstream automation is to automatically resolve `Cargo.lock` conflicts. This is done in two steps:
1. If there is a merge conflict in the lockfile, we automatically resolve that by reverting to our version and then invoking Cargo to update the lockfile. This is committed as part of the merge commit.
2. We then attempt to update the lockfile with Cargo and commit it separately if that results in changes, to handle the case where the merge produced a lockfile with no conflict but that would fail `cargo build --locked`.
In theory this should avoid any lockfile conflict from ever showing up. Unfortunately, before this PR step 1 was done only for `Cargo.lock`, while step 2 was done for both `Cargo.lock` and `src/bootstrap/Cargo.lock`. This means that if a merge …
=> Fix conflict in bootstrap's `Cargo.lock` not being resolved

ferrocene/doc/internal-procedures/src/onboarding.rst
Added the steps to setup CircleCI access, after the debugging I did with Atri to get their account up and running.
=> Add circleci onboarding docs

ferrocene/doc/internal-procedures/src/release/stable.rst, ferrocene/doc/qualification-plan/src/validation.rst
When working with https://app.clickup.com/t/8693u2ge5 I ended up rewriting most of the validation process page... so here we are! Most of the content is new, and in general clarifies the steps that are automated while reducing the manual checks when not strictly needed.
=> Rework the validation process page

ferrocene/doc/safety-manual/src/constraints.rst, ferrocene/doc/safety-manual/src/options.rst
https://ferroussystems.clickup.com/t/8693tyf5g
=> Turn the linker options list in SM into a table

ferrocene/doc/qualification-plan/src/development.rst
Also, the public can also view and review PRs... the paragraph is stale.
=> we do not (yet) define the "authorized" concept anywhere

ferrocene/doc/safety-manual/src/usage.rst
Fixes https://app.clickup.com/t/8693tyhty.
=> Mention .rmeta in "Cleaning the Build Space"

ferrocene/doc/release-notes/src/24.05.0.rst
Fixes https://app.clickup.com/t/8693xud0m.
=> Mention distribution of more dev tools in release notes

ferrocene/doc/safety-manual/src/customer-interactions.rst
The old content was mostly out of date. Fixes https://app.clickup.com/t/8693nv6re
=> Update the content of the customers interactions page

ferrocene/doc/document-list/src/project-documents.rst, ferrocene/doc/document-list/src/reference-documents.rst, ferrocene/doc/evaluation-plan/src/method.rst, ferrocene/doc/evaluation-report/src/potential-errors.rst, ferrocene/doc/evaluation-report/src/tool-analysis.rst
Fixes https://app.clickup.com/t/8693umm77.
=> Convert csv to list tables

.github/workflows/automation-update-lockfiles.yml, ferrocene/tools/update-lockfiles/README.md, ferrocene/tools/update-lockfiles/lockfiles.yml, ferrocene/tools/update-lockfiles/update.py
https://ferroussystems.clickup.com/t/8693tvx4z
=> Implement lockfile update automation

ferrocene/ci/scripts/prepare-docs-to-github-pages.py
Noticed the workflow was failing.
=> Use the new tarball names in the github pages publishing code

ferrocene/doc/safety-manual/src/user-responsibility.rst
Fixes https://ferroussystems.clickup.com/t/8693tydv7.
=> Update user responsibility

ferrocene/doc/safety-manual/src/degraded-environment.rst
=> Update degraded-environment variable listing

ferrocene/doc/internal-procedures/src/release-notes.rst, ferrocene/doc/qualification-plan/src/organization.rst
Fix a small spelling error, add myself to the Ferrocene organization.
=> Update Organization Roster

ferrocene/doc/safety-manual/src/constraints.rst
It is easy to miss that there is another column, because second column is much wider than a standard screen.
=> convert table to sections

ferrocene/tools/self-test/src/binaries.rs, ferrocene/tools/self-test/src/compile.rs, ferrocene/tools/self-test/src/error.rs, ferrocene/tools/self-test/src/linkers.rs, ferrocene/tools/self-test/src/linkers/argparse.rs, ferrocene/tools/self-test/src/main.rs, ferrocene/tools/self-test/src/report.rs, ferrocene/tools/self-test/src/targets.rs, ferrocene/tools/self-test/src/test_utils.rs, ferrocene/tools/self-test/src/utils.rs
I go through the code, try to document it and clean it up, and hope to understand it better at the end.
=> Understand `ferrocene-self-test` by refactoring it

ferrocene/doc/specification/exts/ferrocene_spec_lints/__init__.py, ferrocene/doc/sphinx-shared-resources/requirements.in, ferrocene/doc/sphinx-shared-resources/requirements.txt
This brings the deterministic search index fix we upstreamed: https://github.com/sphinx-doc/sphinx/pull/11665
=> Update Sphinx to the in-development 7.3 version

ferrocene/tools/pull-subtrees/subtrees.yml
Closes #438
Should of been part of https://github.com/ferrocene/ferrocene/pull/348
=> we now maintain the repo in-tree

ferrocene/ci/scripts/calculate-release-job-matrix.py
Johann discovered that if you try to start a manual release with a commit that is not authored by bors and built by CI, you'll get a confusing `AccessDenied` error. To alleviate the problem, this PR checks for the common failure case (someone putting their development branch rather than a bors try commit) and shows a descriptive error in that case.
=> Prevent releasing commits not authored by bors

ferrocene/doc/evaluation-report/src/method.rst
Noticed this while going through the docs with a client.
=> Note that we are not running tests daily

ferrocene/doc/internal-procedures/src/bors.rst, ferrocene/doc/internal-procedures/src/index.rst, ferrocene/doc/qualification-plan/src/infrastructure.rst
Added a small amount of docs on the internal procedures on how to interact with bors!
=> Add some docs on how to interact with bors

ferrocene/tools/self-test/src/binaries.rs
The self-testing tool checks whether all binaries match the expected commit hash, but unfortunately that is broken when building from source. That's because Cargo doesn't pick up any commit hash when building from the source tarball (this is an upstream problem).
While we fix the problem upstream, we need to make the self-testing tool useful in builds from source of 24.05.0. This hacky patch does that by allowing *just Cargo* not to have any hash in its version output. It won't affect binary distribution as there the hash is present.
=> [24.05.0] Skip checking the cargo hash in the self-testing tool if missing

ferrocene/tools/pull-upstream/pull.sh
This should fix the automation failure.
=> Gracefully handle cargo errors when updating the lockfile during pulls

ferrocene/ci/channel, ferrocene/ci/configure.sh
This PR prepares stable release artifacts for Ferrocene 24.05.0, and adds the qualification technical report from TÜV SÜD.
=> Prepare stable artifacts for Ferrocene 24.05.0

ferrocene/tools/pull-upstream/pull.sh
before
> file deleted by Rust
> file deleted by Ferrocene
after
> file deleted upstream
> file deleted in Ferrocene
=> improve file deletion conflict error message

Cargo.lock, ferrocene/tools/self-test/Cargo.toml, ferrocene/tools/self-test/src/main.rs
- is unmaintained
- is 2 less crates to build
=> replace external dep with functionality from std

ferrocene/ci/scripts/llvm-cache.sh
We were not generating a shasum for Windows:
=> Fix sha command use for Windows CI

ferrocene/doc/release-notes/src/24.05.0.rst
This is in preparation for the upcoming release.
=> Remove upcoming mark from the 24.05.0 release

ferrocene/ci/scripts/detect-conflict-markers.py
https://github.com/ferrocene/ferrocene/commit/2ff3053cb0b4dbf2a683137e7f91a2c0d8ea4f3c
=> conflict markers for deleted files need adjustment

ferrocene/doc/user-manual/src/rustc/install.rst
This is a quick PR to add link to CriticalUp instead of placeholder text.
Ticket: https://ferroussystems.clickup.com/t/86947z6md
=> Add pointer to CriticalUp docs.

ferrocene/doc/glossary.rst, ferrocene/doc/user-manual/src/conf.py, ferrocene/doc/user-manual/src/index.rst, ferrocene/doc/user-manual/src/rustfmt/cli.rst, ferrocene/doc/user-manual/src/rustfmt/usage.rst, ferrocene/doc/user-manual/src/terms.rst
=> expand user-manual for rustfmt

ferrocene/doc/safety-manual/src/index.rst, ferrocene/doc/safety-manual/src/rustc/degraded-environment.rst, ferrocene/doc/safety-manual/src/rustfmt/constraints.rst, ferrocene/doc/safety-manual/src/rustfmt/options.rst, ferrocene/doc/safety-manual/src/rustfmt/usage.rst
Do the constraints and tool option make sense?
=> Write `rustfmt` safety manual

ferrocene/doc/qualification-plan/src/standards/iec-61508.rst, ferrocene/doc/qualification-plan/src/standards/iso-26262.rst
=> [1.79] Reduce clutter in the documentation

ferrocene/doc/qualification-plan/src/traceability-matrix.rst
Backport of https://github.com/ferrocene/ferrocene/pull/698
=> [1.77] Reduce clutter in the documentation

ferrocene/doc/qualification-plan/src/traceability-matrix.rst
Backport of https://github.com/ferrocene/ferrocene/pull/698
=> [1.68] Reduce clutter in the documentation

tests/run-make/no-builtins-attribute/no_builtins.rs, tests/run-make/no-builtins-lto/no_builtins.rs, tests/ui/crate-name-attr-used.rs, tests/ui/destructuring-assignment/slice_destructure.rs, tests/ui/destructuring-assignment/slice_destructure_fail.rs, tests/ui/destructuring-assignment/tuple_destructure.rs, tests/ui/destructuring-assignment/tuple_destructure_fail.rs, tests/ui/destructuring-assignment/tuple_struct_destructure.rs, tests/ui/destructuring-assignment/tuple_struct_destructure_fail.rs, tests/ui/empty/empty-attributes.rs, tests/ui/error-codes/E0519.rs, tests/ui/lint/unused/unused-attr-duplicate.rs, tests/ui/target-feature/invalid-attribute.rs, tests/ui/target-feature/tied-features.rs
This just adds a few more annotations for some that only have a single test associated (there are still more)
=> Add more annotations for single tested only paragraphs

ferrocene/doc/qualification-report/src/requirements-traceability.rst
See https://github.com/rust-lang/rust/pull/126254
=> now also available on non-host platforms

ferrocene/doc/specification/CONTRIBUTING.rst, ferrocene/doc/specification/exts/ferrocene_spec/__init__.py, ferrocene/doc/specification/exts/ferrocene_spec/definitions/__init__.py, ferrocene/doc/specification/exts/ferrocene_spec/sphinx_fixes.py, ferrocene/doc/specification/exts/ferrocene_spec/syntax_directive.py, ferrocene/doc/specification/src/attributes.rst, ferrocene/doc/specification/src/changelog.rst, ferrocene/doc/specification/src/conf.py, ferrocene/doc/specification/src/entities-and-resolution.rst, ferrocene/doc/specification/src/expressions.rst, ferrocene/doc/specification/src/ffi.rst, ferrocene/doc/specification/src/functions.rst, ferrocene/doc/specification/src/general.rst, ferrocene/doc/specification/src/generics.rst, ferrocene/doc/specification/src/glossary.rst, ferrocene/doc/specification/src/index.rst, ferrocene/doc/specification/src/lexical-elements.rst, ferrocene/doc/specification/src/macros.rst, ferrocene/doc/specification/src/ownership-and-deconstruction.rst, ferrocene/doc/specification/src/patterns.rst, ferrocene/doc/specification/src/program-structure-and-compilation.rst, ferrocene/doc/specification/src/statements.rst, ferrocene/doc/specification/src/types-and-traits.rst
=> [1.79] Bump specification

ferrocene/doc/internal-procedures/src/index.rst, ferrocene/doc/internal-procedures/src/working-with-the-ci.rst
In this document I tried to explain some common procedures/setup around the CI and imitating it.
It's pretty rough and uses very casual language, but it's a starting point.
Since I'm already familiar with much of the CI, I'd appreciate getting feedback from folks who fiddle with it less about what should be added / tweaked.
=> Create a document offering guidance to imitating the CI

ferrocene/doc/document-list/signature/signature.toml, ferrocene/doc/evaluation-plan/signature/signature.toml, ferrocene/doc/evaluation-report/signature/signature.toml, ferrocene/doc/qualification-plan/signature/signature.toml, ferrocene/doc/qualification-report/signature/signature.toml, ferrocene/doc/safety-manual/signature/signature.toml
=> Signatures for Ferrocene 24.08.0 by Florian Gilcher

.circleci/workflows.yml
3508cde815941317a8a5ee81c8de9c9854fdb53a made this obsolete
=> remove obsolete invocation

ferrocene/ci/configure.sh
Addresses https://github.com/ferrocene/ferrocene/issues/788
=> Repair ferrocene.document-signatures option

ferrocene/doc/evaluation-report/src/rustc/method.rst
all tests are run even for non-code changes
=> remove ambiguity

ferrocene/tools/pull-upstream/pull.sh
We need to remind to move the ferrocene annotations
=> more correct instruction

compiler/rustc_const_eval/messages.ftl, compiler/rustc_const_eval/src/interpret/eval_context.rs, compiler/rustc_middle/src/mir/syntax.rs, ferrocene/doc/document-list/signature/signature.toml, ferrocene/doc/qualification-report/signature/signature.toml, src/tools/miri/tests/fail/storage-live-dead-var.rs, src/tools/miri/tests/fail/storage-live-dead-var.stderr, src/tools/miri/tests/fail/storage-live-resets-var.rs, src/tools/miri/tests/fail/storage-live-resets-var.stderr
Backports:
- https://github.com/rust-lang/rust/pull/127364
- https://github.com/rust-lang/rust/pull/126154
=> Backport two soundness fixes to 1.79

ferrocene/doc/document-list/signature/signature.toml, ferrocene/doc/qualification-report/signature/signature.toml, ferrocene/doc/release-notes/src/24.08.0.rst
=> Signatures 24.08.0

ferrocene/doc/document-list/signature/signature.toml, ferrocene/doc/qualification-report/signature/signature.toml, tests/codegen/ferrocene/jump-threading-floats.rs, tests/codegen/ferrocene/miscompile_127286.rs, tests/ui/ferrocene/consts/storage-live-on-live.rs, tests/ui/ferrocene/llvm/no-segfault.rs
- `tests/ui/ferrocene/llvm/no-segfault.rs` tests [issue#127260](https://github.com/rust-lang/rust/issues/127260) which was fixed by the backported [PR#127364](https://github.com/rust-lang/rust/pull/127364) 
- `tests/ui/ferrocene/consts/storage-live-on-live.rs` tests [issue#119366](https://github.com/rust-lang/rust/issues/119366) which was fixed by the backported [PR#126154](https://github.com/rust-lang/rust/pull/126154)
- `tests/codegen/ferrocene/miscompile_127286.rs` tests [issue#127286](https://github.com/rust-lang/rust/issues/127286) which was fixed by the backported [PR#127364](https://github.com/rust-lang/rust/pull/127364)
=> Add tests for backports

ferrocene/doc/document-list/signature/signature.toml, ferrocene/doc/qualification-report/signature/signature.toml
Signing off on the fixed version of 24.08.0
=> Florians signatures for 24.08.0

.circleci/workflows.yml, ferrocene/ci/docker-images/ubuntu-24/Dockerfile, ferrocene/ci/scripts/emulated-aarch64-qnx-test-runner.sh, ferrocene/ignored-tests.toml, library/std/src/error/tests.rs, library/std/src/process/tests.rs
this PR depends on #780 and includes its commits. only commits starting with "add script to prepare and run aarch64 QNX VM" belong to this PR
=> run tests on aarch64 QNX

ferrocene/ignored-tests.toml, tests/ui/structs-enums/enum-rec/issue-17431-6.rs, tests/ui/structs-enums/enum-rec/issue-17431-6.stderr
works around rust-lang/rust#129315
=> QNX: replace Mutex with UnsafeCell to fix UI test

ferrocene/doc/document-list/signature/signature.toml, ferrocene/doc/qualification-report/signature/signature.toml
Signing procedure for the next Ferrocene release.
=> Florians Signatures for 2024.08, 20/08/2024

ferrocene/tools/pull-upstream/pull.sh
this resulted in library/Cargo.lock remaining stale
=> add missing char

ferrocene/ci/channel, ferrocene/ci/configure.sh
This PR bumps the channel name and uploads the TÜV SÜD technical report. [Release process docs](https://public-docs.ferrocene.dev/main/qualification/internal-procedures/release/stable.html)
=> Prepare release artifacts for Ferrocene 24.08.0

ferrocene/doc/internal-procedures/src/working-with-the-ci.rst
Recently `uv` got some updates and it can now manage your Python for you! Woo!
=> Reflect recent uv updates in CI docs

ferrocene/doc/internal-procedures/src/working-with-the-ci.rst
https://github.com/ferrocene/ferrocene/pull/873#discussion_r1732368880
=> Correct the uv run example

.circleci/config.yml, .circleci/workflows.yml, bors.toml
Post #867, this should remove the no longer required circleCI jobs.
=> Turn off CircleCI for commits

.github/workflows/automation-backport.yml
This should fix the broken backport job.
=> Give access to the automations token to `automation-backport`

ferrocene/doc/internal-procedures/signature/config.toml
Update the signature for internal procedures temporarily.
=> Update signature for internal procedures

ferrocene/doc/release-notes/src/24.11.0.rst, ferrocene/doc/release-notes/src/index.rst, ferrocene/doc/release-notes/src/next.rst
This shouldn't be merged until https://github.com/ferrocene/ferrocene/pull/952 is.
=> Prepare 24.11 release notes

ferrocene/doc/specification/src/attributes.rst, ferrocene/doc/specification/src/changelog.rst, ferrocene/doc/specification/src/expressions.rst, ferrocene/doc/specification/src/glossary.rst, ferrocene/doc/specification/src/patterns.rst, ferrocene/doc/specification/src/types-and-traits.rst, ferrocene/doc/specification/src/values.rst
https://github.com/ferrocene/ferrocene/pull/763
https://github.com/ferrocene/ferrocene/pull/815
https://github.com/ferrocene/ferrocene/pull/940
https://github.com/ferrocene/ferrocene/pull/972
=> Backport specification changes

ferrocene/doc/internal-procedures/src/subtree-pulls.rst, ferrocene/tools/pull-subtrees/pull.py
- **Emit a warning if `--subtree` is unused**
- **Document how to pull single subtrees**
=> Improve UX when pulling a single subtree

ferrocene/doc/internal-procedures/src/subtree-pulls.rst
This describe the procedure in #1004
=> backtrace is different for historical reasons

Cargo.toml, src/bootstrap/src/ferrocene/dist.rs
=> [1.81] Add rustc-perf site to vendor tarball

.github/actions/setup/action.yml, .github/workflows/commit.yml, ferrocene/ci/scripts/setup-ubuntu.sh
In our setup action we falsely assumed that composite actions could take booleans, they cannot.
Also mmakes us no longer blindly `apt upgrade` as there is zero point, we build artifacts in docker containers that are no more than a week old.
=> Repair setup action misconceptions

ferrocene/ci/scripts/calculate_parameters.py, ferrocene/doc/release-notes/src/next.rst, ferrocene/doc/user-manual/src/targets/index.rst, ferrocene/tools/self-test/src/targets.rs
=> Add riscv64-gnu to self-test

.circleci/config.yml, .circleci/workflows.yml, .github/actions/setup/action.yml, REUSE.toml, ferrocene/ci/scripts/setup-venv.sh
#1048 seems to be encountering some issues due to some recent changes to uv, this adjusts to meet those and also version locks us to prevent future issues.
=> Adjust things to meet uv changes (and version lock uv)

tests/run-make/reset-codegen-1/rmake.rs, tests/ui/errors/pic-linker.rs, tests/ui/imports/auxiliary/simple-dylib.rs
We missed this when we pulled some upstream changes.
=> Restore missing annotations

ferrocene/doc/internal-procedures/src/working-with-the-ci.rst
=> Document how to share folders with the containers

ferrocene/ignored-tests.toml
Fixed in https://github.com/ferrocene/ferrocene/pull/1046
=> un-ignore test that has since been fixed

ferrocene/doc/qualification-plan/src/kp-tracking.rst
This is a bit over explanatory...
The field exist only in the manual as it is generated by the KP tool.
=> adding new field in the manual

ferrocene/doc/internal-procedures/src/working-with-the-ci.rst
Takes a shot at clarifying and improving our `uv` docs.
=> Add more uv docs

ferrocene/doc/release-notes/src/24.11.0.rst
this is a port of https://github.com/ferrocene/ferrocene/pull/988
=> port some release/1.81 changes to main

ferrocene/tools/pull-subtrees/pull.py
like we do for upstream pulls. this way automation should always open a PR
=> pull-subtrees: commit merge conflicts

.circleci/workflows.yml, ferrocene/ci/configure.sh, ferrocene/ci/scripts/calculate_parameters.py, ferrocene/packages.toml
Reverts ferrocene/ferrocene#1167
=> Revert "ci: temporarily disable qnx jobs"

ferrocene/tools/common/pr_links.py
See https://ferrous.zulipchat.com/#narrow/channel/455918-Ferrocene.2FPR-rotation/topic/upstream.20pull.20failure.20due.20to.20deleted.20issue
=> Handle deleted PR in the automation body generation

.github/workflows/automation-pull-subtrees.yml, ferrocene/ci/scripts/github_app_auth.py, ferrocene/tools/pull-subtrees/pull.py
=> Make the subtree pull automation use uv as well

ferrocene/tools/pull-subtrees/pull.py
I messed up https://github.com/ferrocene/ferrocene/pull/1201
=> Repair pyyaml declaration

ferrocene/tools/pull-upstream/pull.sh
Description of the problem is in the code comments.
=> Fix pull failing when upstream converts a submodule into a subtree

ferrocene/doc/specification/src/attributes.rst, ferrocene/doc/specification/src/changelog.rst, ferrocene/doc/specification/src/conf.py, ferrocene/doc/specification/src/expressions.rst, ferrocene/doc/specification/src/ffi.rst, ferrocene/doc/specification/src/functions.rst, ferrocene/doc/specification/src/general.rst, ferrocene/doc/specification/src/glossary.rst, ferrocene/doc/specification/src/inline-assembly.rst, ferrocene/doc/specification/src/items.rst, ferrocene/doc/specification/src/lexical-elements.rst, ferrocene/doc/specification/src/macros.rst, ferrocene/doc/specification/src/patterns.rst, ferrocene/doc/specification/src/types-and-traits.rst, ferrocene/doc/specification/src/values.rst, ferrocene/doc/specification/version.rst
Subtree update of specification
=> [1.83] Update specification

ferrocene/ci/scripts/calculate-release-job-matrix.py, ferrocene/ci/scripts/calculate_parameters.py, ferrocene/ci/scripts/github_app_auth.py, ferrocene/ci/scripts/utils/pyproject.toml
Forgot to do this in the previous PR.
=> Pin versions used in uv scripts

ferrocene/doc/release-notes/src/25.02.0.rst
Thanks @Dajamante for building this list.
Adds a list of fixed KPs to the 25.02 release notes.
=> Add fixed KPs to 25.02 release notes

ferrocene/doc/user-manual/src/overview.rst
This was requested by our assessor.
=> Add cargo and rustdoc versions to overview

.circleci/workflows.yml, compiler/rustc_target/src/spec/targets/thumbv7em_ferrocenecoretest_eabi.rs, compiler/rustc_target/src/spec/targets/thumbv7em_ferrocenecoretest_eabihf.rs, ferrocene/ignored-tests.toml, library/unwind/src/lib.rs, tests/ui/ferrocene/compiler-arguments/upper_c_linker-flavor/upper_c_linker-flavor_eq.rs, tests/ui/ferrocene/compiler-arguments/upper_c_linker-flavor/upper_c_linker-flavor_repeat-diff.rs, tests/ui/ferrocene/compiler-arguments/upper_c_linker-flavor/upper_c_linker-flavor_repeat.rs, tests/ui/ferrocene/compiler-arguments/upper_c_linker-flavor/upper_c_linker-flavor_space-eq.rs, tests/ui/macros/rfc-2011-nicer-assert-messages/assert-with-custom-errors-does-not-create-unnecessary-code.rs, tests/ui/macros/rfc-2011-nicer-assert-messages/feature-gate-generic_assert.rs, tests/ui/structs-enums/multiple-reprs.rs
=> address remaining ARMv7E-M test failures

ferrocene/tools/pull-upstream/automation.py, ferrocene/tools/pull-upstream/pull.sh
This PR fixes the last issues with the pull upstream automation. I managed to fully run the script locally and generate a working PR, so no more fixes should be necessary. Example of a generated PR: https://github.com/ferrocene/ferrocene/pull/1239
=> Fix upstream pulling

ferrocene/doc/safety-manual/src/customer-interactions.rst, ferrocene/doc/safety-manual/src/known-problems.rst
This PR expands the documentation about known problems to clarify how to access the database and the ways to know about new KPs being discovered.
=> Update known problems documentation

ferrocene/doc/release-notes/src/25.02.0.rst
=> [1.83] Remove upcoming on 25.02

ferrocene/doc/release-notes/src/25.02.0.rst
=> Fix spelling in 25.02 release notes

ferrocene/doc/release-notes/src/25.02.0.rst, tests/ui/ferrocene/problems/kp_issue_124364.rs
This PR backports the following PRs to the `release/1.83` branch:
* #1256
* #1268
=> [1.83] Last backports

ferrocene/doc/release-notes/src/25.02.0.rst
=> Add aarch64-apple-darwin QM to release notes

ferrocene/doc/internal-procedures/src/known-problems.rst, ferrocene/doc/internal-procedures/src/subtree-pulls.rst, ferrocene/doc/user-manual/src/rustfmt/usage.rst
Review for 25.02 found no issues that need action.
This PR collects small fixes found during reading that do not merit a backport.
=> Small changes found during docs review for 25.02

.github/workflows/docs-to-github-pages.yml
See https://github.com/ferrocene/ferrocene/actions/runs/13133873078/job/36644789822 failing
=> Bump actions/upload-pages-artifact to v3

src/bootstrap/src/ferrocene/doc.rs
This was discovered on Friday during document signing. If in the same bootstrap invocation documents are built both fresh (due to a signature) and not fresh, the `BreadcrumbsAssets` step would only be executed once, resulting in one of the builds not having the breadcrumbs. To fix the problem we stop using a step to copy the breadcrumbs, and instead invoke a function.
=> Fix breadcrumbs not being copied if docs are built both fresh and not fresh

ferrocene/tools/pull-upstream/pull.sh
For a long time upstream has been using unstable features in their `Cargo.toml`s, which required us to change the pull script to use `RUSTC_BOOTSTRAP=1` whenever we need to invoke Cargo. That worked well until a few days ago, when upstream stabilized one of those features. Unfortunately, `RUSTC_BOOTSTRAP=1` works only when the feature is unstable, not when the feature is stabilized on the nightly channel but hasn't reached the stable channel yet.
This PR properly solves the problem by enforcing the use of a nightly toolchain when running the pull script.
=> Enforce the use of nightly Cargo when pulling from upstream

ferrocene/doc/release-notes/src/next.rst, ferrocene/doc/user-manual/src/index.rst, ferrocene/doc/user-manual/src/targets/index.rst, ferrocene/doc/user-manual/src/targets/thumbv7em-none-eabi.rst, ferrocene/doc/user-manual/src/targets/thumbv7em-none-eabihf.rst
We now quality manage ARMv7E-M targets. 🎉
=> Quality Manage ARMv7E-M

ferrocene/tools/document-signatures/src/verify.rs
Forward port of a commit from #1277
=> Improve check signatures debugging

ferrocene/doc/qualification-plan/src/ci.rst
=> Refer to GHA for commit checks, not Circle

.github/workflows/commit.yml, ferrocene/ci/scripts/fix-stage0-branch.py, ferrocene/tools/pull-upstream/pull.sh, src/stage0
This will fix the expected automation breakage from https://github.com/ferrocene/ferrocene/pull/1278.
=> Backport #1278 to 1.84

.github/workflows/commit.yml, ferrocene/ci/scripts/fix-stage0-branch.py, ferrocene/tools/pull-upstream/pull.sh, src/stage0
This will fix the expected automation breakage from #1278.
=> Backport #1278 to 1.85

ferrocene/doc/internal-procedures/src/testing-other-targets.rst
#1282 now makes this required.
=> Specify CPU in testing-other-targets document

.circleci/workflows.yml, ferrocene/doc/qualification-report/exts/ferrocene_test_outcomes/render_template.py, ferrocene/doc/qualification-report/src/index.rst, ferrocene/doc/qualification-report/src/rustc/thumbv7em-none-eabi.rst, ferrocene/doc/qualification-report/src/rustc/thumbv7em-none-eabihf.rst, ferrocene/doc/qualification-report/src/templates/tests.jinja2, ferrocene/doc/user-manual/src/targets/index.rst, ferrocene/doc/user-manual/src/targets/thumbv7em-none-eabi.rst, ferrocene/doc/user-manual/src/targets/thumbv7em-none-eabihf.rst
Marks the thumbv7e-m qualification as coming soon!
=> Mark thumbv7e-m as qualification coming soon

ferrocene/doc/internal-procedures/src/backports.rst
I understood "development" as any change that happens, including maintenance work like fixing bugs, but others understood it differently
=> "development" is unclear on its own

ferrocene/doc/qualification-plan/src/organization.rst
Pietro and I swapped around our roles a bit.
=> Update a couple team roles

.github/dependabot.yml
I did not find this information quick/easy to find on github docs, so adding here for convenience
=> link to dependabot reference

tests/ui/async-await/async-closures/ferrocene-annotations, tests/ui/static/raw-ref-deref-with-unsafe.rs, tests/ui/static/raw-ref-deref-without-unsafe.rs, tests/ui/static/raw-ref-static-mut.rs, tests/ui/traits/dyn-drop-principal.rs, tests/ui/traits/dyn-star-drop-principal.rs
These tests cover the changed paragraphs from 1.84 and 1.85These tests cover the changed paragraphs from 1.84 and 1.85
=> Annotate tests for new and edited specification paragraphs

ferrocene/doc/specification/.github/workflows/ci.yml, ferrocene/doc/specification/src/associated-items.rst, ferrocene/doc/specification/src/changelog.rst, ferrocene/doc/specification/src/conf.py, ferrocene/doc/specification/src/entities-and-resolution.rst, ferrocene/doc/specification/src/expressions.rst, ferrocene/doc/specification/src/glossary.rst, ferrocene/doc/specification/src/lexical-elements.rst, ferrocene/doc/specification/src/macros.rst, ferrocene/doc/specification/src/ownership-and-deconstruction.rst, ferrocene/doc/specification/src/types-and-traits.rst, ferrocene/doc/specification/version.rst
=> Fix spec diverge (again)

ferrocene/doc/internal-procedures/src/docs/signatures.rst, ferrocene/doc/internal-procedures/src/setup-local-env.rst
Turns out a change was made while I was on leave removing the need to agree to your email address being published. Also, the third bullet point was worded in a confusing way. This PR reworks that section to address those concerns.
=> Small improvement to the signing docs

ferrocene/doc/specification/.github/workflows/ci.yml, ferrocene/doc/specification/src/associated-items.rst, ferrocene/doc/specification/src/changelog.rst, ferrocene/doc/specification/src/conf.py, ferrocene/doc/specification/src/entities-and-resolution.rst, ferrocene/doc/specification/src/expressions.rst, ferrocene/doc/specification/src/glossary.rst, ferrocene/doc/specification/src/lexical-elements.rst, ferrocene/doc/specification/src/macros.rst, ferrocene/doc/specification/src/ownership-and-deconstruction.rst, ferrocene/doc/specification/src/types-and-traits.rst, ferrocene/doc/specification/version.rst
=> [1.86] Backport some spec changes

ferrocene/tools/pull-upstream/pull.sh
=> pull-upstream: ignore fix-stage0-branch.py errors

.circleci/workflows.yml, ferrocene/ci/configure.sh, ferrocene/packages.toml, src/bootstrap/src/ferrocene/partners/oxidos.rs
Following from https://github.com/ferrocene/ferrocene/pull/1317 and https://github.com/ferrocene/ferrocene/commit/bbf674cdef2d30d574650048e8b22f2e3d5dd853
=> Re-enable oxidos

.circleci/workflows.yml, ferrocene/ci/configure.sh, ferrocene/packages.toml, src/bootstrap/src/ferrocene/partners/oxidos.rs
Manual backports of #1411 and #1441
=> [1.86] Manual backporting

RELEASES.md, ferrocene/doc/release-notes/src/25.05.0.rst, ferrocene/doc/release-notes/src/index.rst, ferrocene/doc/release-notes/src/next.rst, ferrocene/doc/user-manual/src/targets/thumbv7em-none-eabi.rst, ferrocene/doc/user-manual/src/targets/thumbv7em-none-eabihf.rst, src/tools/linkchecker/main.rs
Add the release notes for next release: 25.05! :)
=> Add 25.05 release notes

ferrocene/doc/internal-procedures/src/subtree-pulls.rst
The format of the argument to use is not obvious, so documenting it here.
=> doc: show the format to use when doing a manual subtree pull

ferrocene/doc/internal-procedures/src/docs/signatures.rst
=> Clarify that cosign is installed automatically

src/bootstrap/defaults/bootstrap.ferrocene-dist.toml
=> avoid bootstrap warnings

.circleci/workflows.yml
I do not know why we are doing this, so checking...
=> ci: do not build stage 1 rustdoc

src/bootstrap/src/ferrocene/doc/mod.rs
I was unable to run `./x.py test bootstrap` since a recent upstream pull as some of these tests use `--dry-run` and have an `out` path which is not relative to the `src`.
```
thread 'core::builder::tests::snapshot::test_exclude_kind' panicked at src/bootstrap/src/ferrocene/doc/mod.rs:876:41:
called `Result::unwrap()` on an `Err` value: StripPrefixError(())
```
Fixing this correctly is rather hard since in distribution builds Sphinx needs to be given paths relative to it's `conf.py`. Instead, we simply return `path` during `dry-run` since reproducability is not a concern during dry runs.
=> Fix relative_path in dry_run to make bootstrap tests pass locally

ferrocene/doc/specification/src/attributes.rst, ferrocene/doc/specification/src/changelog.rst, ferrocene/doc/specification/src/inline-assembly.rst
- 2 features need to be checked if they need to be documented
=> Document Rust 1.88

ferrocene/doc/release-notes/src/25.08.0.rst, ferrocene/doc/release-notes/src/index.rst, ferrocene/doc/release-notes/src/next.rst
=> Add 25.08 release notes

library/core/src/cmp.rs, library/core/src/panic.rs, library/core/src/ub_checks.rs, library/coretests/tests/option.rs
- **Document uncovered lines**
- **Raise `core::option` coverage to 100%**
cc @Hoverbear @Urhengulas
=> Final coverage fixes for subset

.circleci/workflows.yml, compiler/rustc_driver_impl/src/lib.rs
=> Revert #1687

ferrocene/doc/specification/src/conf.py, ferrocene/doc/specification/version.rst, ferrocene/tools/pull-subtrees/pull.py, license-metadata.json
Found these as I was looking at why upstream FLS pulls fail
=> some cleaning of Python code

src/bootstrap/src/core/build_steps/dist.rs, src/bootstrap/src/core/builder/mod.rs
=> bootstrap: cleaning some changes specific to Ferrocene

ferrocene/doc/release-notes/src/25.08.0.rst
Seems we forgot this before. 😅
=> Add the core cert to the release notes

ferrocene/doc/core-certification/signature/signature.toml, ferrocene/doc/document-list/signature/signature.toml, ferrocene/doc/evaluation-plan/signature/signature.toml, ferrocene/doc/evaluation-report/signature/signature.toml, ferrocene/doc/internal-procedures/signature/signature.toml, ferrocene/doc/qualification-plan/signature/signature.toml, ferrocene/doc/qualification-report/signature/signature.toml, ferrocene/doc/release-notes/src/25.08.0.rst, ferrocene/doc/safety-manual/signature/signature.toml
=> [1.88] Add the core cert to the release notes

ferrocene/ci/configure.sh
In #1527 we renamed the facades and didn't get everything.
Thanks @japaric for pointing it out!
=> Re-enable profiler on facades

ferrocene/doc/core-certification/signature/signature.toml, ferrocene/doc/document-list/signature/signature.toml, ferrocene/doc/evaluation-plan/signature/signature.toml, ferrocene/doc/evaluation-report/signature/signature.toml, ferrocene/doc/internal-procedures/signature/signature.toml, ferrocene/doc/qualification-plan/signature/signature.toml, ferrocene/doc/qualification-report/signature/signature.toml, ferrocene/doc/release-notes/src/25.08.0.rst, ferrocene/doc/safety-manual/signature/signature.toml
=> [1.88] update release notes

ferrocene/doc/core-certification/signature/signature.toml, ferrocene/doc/document-list/signature/signature.toml, ferrocene/doc/evaluation-plan/signature/signature.toml, ferrocene/doc/evaluation-report/signature/signature.toml, ferrocene/doc/internal-procedures/signature/signature.toml, ferrocene/doc/qualification-plan/signature/signature.toml, ferrocene/doc/qualification-report/signature/signature.toml, ferrocene/doc/release-notes/src/25.08.0.rst, ferrocene/doc/safety-manual/signature/signature.toml
=> Release notes typo: We are not removing core cert, it's just a preview
